"""Renal dose adjustment rules for Indian OPD prescribing.

Sources: KDIGO 2022 CKD guidelines (eGFR staging: G1>=90, G2 60-89, G3a 45-59,
G3b 30-44, G4 15-29, G5<15); FDA drug labels (accessdata.fda.gov); Lexicomp
renal dosing database; FDA Drug Safety Communication 2016 (metformin); MHRA
Drug Safety Update 2014 (nitrofurantoin); HSA Singapore Safety Alert
(glibenclamide); AstraZeneca SGLT2i eGFR dosing chart (dapagliflozin);
EMPA-KIDNEY trial, Clin Kidney J 2023 (empagliflozin); AJKD Core Curriculum
2022 (diabetes + CKD, glimepiride/insulin); Psychiatric Times / Int J Bipolar
Disord CKD-lithium review (lithium); Frontiers Pharmacol 2025,
10.3389/fphar.2025.1703557 (methotrexate); American College of Rheumatology
gout guideline (allopurinol, colchicine).

All alerts are DOCTOR-FACING DECISION SUPPORT ONLY. This module never
auto-modifies a prescription, dose, or diagnosis -- every alert requires
explicit doctor review and action at the point of care.

No India-specific renal-dosing outcome data exists for most of these drugs;
thresholds below are global (FDA/EMA/KDIGO/Lexicomp) pharmacology consensus,
not Indian-population-specific studies. Indian brand names are included in
drug_terms only where the mapping to generic name is well established.
"""

_RENAL_ADJUSTMENT_RULES: list[dict] = [
    {
        "drug_terms": {'metformin', 'glyciphage', 'gluformin', 'glycomet'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'avoid_below_30_caution_30_to_45',
        "action": 'reduce_dose',
        "urgency": 'critical',
        "alert": 'Metformin: avoid if eGFR<30; do not initiate 30-45; reassess if falls <45',
        "rationale": 'Contraindicated below eGFR 30 due to lactic acidosis risk; initiation not recommended 30-45. Source: FDA Drug Safety Communication 2016.',
    },
    {
        "drug_terms": {'ciplox', 'ciprofloxacin'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_below_30',
        "action": 'reduce_dose',
        "urgency": 'medium',
        "alert": 'Ciprofloxacin: reduce dose/frequency if eGFR<30 (CNS, tendon toxicity risk)',
        "rationale": 'Renally cleared fluoroquinolone; dose reduction required in moderate-severe CKD to avoid accumulation. Source: Lexicomp renal dosing.',
    },
    {
        "drug_terms": {'levofloxacin', 'levoflox'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_below_50',
        "action": 'reduce_dose',
        "urgency": 'medium',
        "alert": 'Levofloxacin: reduce dose/extend interval if eGFR<50',
        "rationale": 'Predominantly renally excreted; standard dosing regimens require adjustment below CrCl 50 mL/min. Source: Lexicomp renal dosing.',
    },
    {
        "drug_terms": {'nitrofurantoin', 'macrobid', 'nitrofur', 'furadantin'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'avoid_below_45',
        "action": 'avoid',
        "urgency": 'high',
        "alert": 'Nitrofurantoin: avoid if eGFR<45 - ineffective + risk of toxicity accumulation',
        "rationale": 'Reduced renal secretion below eGFR 45 lowers urinary drug levels (treatment failure) and raises systemic toxicity risk. Source: MHRA Drug Safety Update 2014.',
    },
    {
        "drug_terms": {'cotrimoxazole', 'bactrim', 'trimethoprim-sulfamethoxazole', 'co-trimoxazole', 'septran'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_50pct_15_to_30_avoid_below_15',
        "action": 'reduce_dose',
        "urgency": 'high',
        "alert": 'Cotrimoxazole: reduce dose 50% if eGFR 15-30; avoid if eGFR<15. Watch K+, creatinine',
        "rationale": 'Nephrotoxic and causes hyperkalemia (trimethoprim blocks distal K+ secretion); dose reduction required below eGFR 30. Source: FPnotebook/UNMC renal dosing guidelines.',
    },
    {
        "drug_terms": {'amoxil', 'mox', 'novamox', 'amoxicillin'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_below_30',
        "action": 'reduce_dose',
        "urgency": 'medium',
        "alert": 'Amoxicillin: reduce dose/extend interval if eGFR<30',
        "rationale": 'Renally eliminated penicillin; interval extension recommended in severe renal impairment to avoid accumulation. Source: Lexicomp renal dosing.',
    },
    {
        "drug_terms": {'cephalexin'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_below_30',
        "action": 'reduce_dose',
        "urgency": 'medium',
        "alert": 'Cephalexin: reduce dose/extend interval if eGFR<30',
        "rationale": 'Renally cleared cephalosporin requiring dose/interval adjustment in moderate-severe CKD. Source: Lexicomp renal dosing.',
    },
    {
        "drug_terms": {'cefixime', 'zifi', 'taxim-o'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_below_20',
        "action": 'reduce_dose',
        "urgency": 'medium',
        "alert": 'Cefixime: reduce dose ~50% if eGFR<20',
        "rationale": 'Renal elimination reduced in severe impairment; dose reduction recommended below CrCl 20 mL/min. Source: Lexicomp renal dosing.',
    },
    {
        "drug_terms": {'gentamicin', 'genticyn'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'any_renal_impairment',
        "action": 'avoid',
        "urgency": 'critical',
        "alert": 'Gentamicin: avoid in OPD/CKD - nephrotoxic + ototoxic, needs levels/hospital dosing',
        "rationale": 'Aminoglycoside with narrow therapeutic index; nephrotoxicity and ototoxicity risk rises sharply with reduced renal clearance and requires level monitoring not feasible in OPD. Source: Lexicomp renal dosing.',
    },
    {
        "drug_terms": {'vancomycin'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'any_renal_impairment',
        "action": 'avoid',
        "urgency": 'critical',
        "alert": 'Vancomycin: avoid in OPD/CKD - nephrotoxic, requires levels + hospital dosing',
        "rationale": 'Renally cleared with narrow therapeutic index; dosing must be individualized to levels and renal function, not appropriate for unmonitored OPD use. Source: Lexicomp renal dosing.',
    },
    {
        "drug_terms": {'digoxin', 'lanoxin'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_below_60',
        "action": 'reduce_dose',
        "urgency": 'high',
        "alert": 'Digoxin: reduce dose if eGFR<60 - narrow therapeutic index, toxicity risk',
        "rationale": 'Predominantly renally excreted; reduced clearance in CKD raises serum levels and risk of digoxin toxicity (arrhythmia, GI, visual symptoms). Source: Lexicomp renal dosing.',
    },
    {
        "drug_terms": {'tenormin', 'atenolol', 'aten'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_below_35',
        "action": 'reduce_dose',
        "urgency": 'medium',
        "alert": 'Atenolol: reduce dose if eGFR<35 (renally cleared beta-blocker)',
        "rationale": 'Predominantly renally eliminated; accumulation below CrCl 35 mL/min can cause bradycardia/hypotension. Source: Lexicomp renal dosing.',
    },
    {
        "drug_terms": {'lisinopril'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'any_renal_impairment',
        "action": 'monitor_closely',
        "urgency": 'high',
        "alert": 'Lisinopril (ACEi): check K+/creatinine in 1-2 weeks after start/dose change in CKD',
        "rationale": 'ACE inhibitors can cause hyperkalemia and acute creatinine rise, especially with volume depletion or bilateral renal artery stenosis; renoprotective but needs monitoring. Source: KDIGO 2022 CKD guideline.',
    },
    {
        "drug_terms": {'ramipril', 'cardace'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'any_renal_impairment',
        "action": 'monitor_closely',
        "urgency": 'high',
        "alert": 'Ramipril (ACEi): check K+/creatinine in 1-2 weeks after start/dose change in CKD',
        "rationale": 'ACE inhibitors can cause hyperkalemia and acute creatinine rise, especially with volume depletion; renoprotective but needs monitoring. Source: KDIGO 2022 CKD guideline.',
    },
    {
        "drug_terms": {'losar', 'covance', 'losartan'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'any_renal_impairment',
        "action": 'monitor_closely',
        "urgency": 'high',
        "alert": 'Losartan (ARB): check K+/creatinine in 1-2 weeks after start/dose change in CKD',
        "rationale": 'ARBs can cause hyperkalemia and acute creatinine rise in CKD, especially combined with volume depletion or NSAIDs; needs monitoring. Source: KDIGO 2022 CKD guideline.',
    },
    {
        "drug_terms": {'spironolactone', 'aldactone'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'avoid_below_30_caution_30_to_60',
        "action": 'avoid',
        "urgency": 'high',
        "alert": 'Spironolactone: avoid if eGFR<30, use with caution + monitor K+ 30-60',
        "rationale": 'Potassium-sparing diuretic carries high hyperkalemia risk that rises sharply as eGFR falls, especially combined with ACEi/ARB. Source: KDIGO 2022 CKD guideline.',
    },
    {
        "drug_terms": {'lasix', 'furosemide'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'any_renal_impairment',
        "action": 'monitor_closely',
        "urgency": 'medium',
        "alert": 'Furosemide: higher doses may be needed in CKD; monitor electrolytes/volume status',
        "rationale": 'Loop diuretics remain effective in CKD (unlike thiazides) but often need dose escalation; monitor for electrolyte disturbance and dehydration/AKI. Source: KDIGO 2022 CKD guideline.',
    },
    {
        "drug_terms": {'folitrax', 'methotrexate'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'avoid_below_30_reduce_dose_30_to_60',
        "action": 'avoid',
        "urgency": 'critical',
        "alert": 'Methotrexate: avoid if eGFR<30; reduce dose 30-60; risk of myelosuppression/toxicity',
        "rationale": 'Renally excreted (70-90% clearance); contraindicated in advanced CKD (CrCl<30) and requires dose reduction in stage 3 CKD due to accumulation and marrow/mucosal toxicity. Source: Frontiers Pharmacol 2025 (PMID 10.3389/fphar.2025.1703557).',
    },
    {
        "drug_terms": {'nsaids', 'ibuprofen', 'naproxen', 'voveran', 'diclofenac', 'nsaid', 'combiflam'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'avoid_below_30_caution_30_to_60',
        "action": 'avoid',
        "urgency": 'critical',
        "alert": 'NSAIDs: avoid if eGFR<30 or known CKD - high acute kidney injury risk',
        "rationale": 'NSAIDs reduce renal prostaglandin-mediated perfusion, precipitating acute kidney injury and accelerating CKD progression; avoid or use minimal duration with caution in CKD. Source: KDIGO 2022 CKD guideline.',
    },
    {
        "drug_terms": {'gabapin', 'gabapentin'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_below_60',
        "action": 'reduce_dose',
        "urgency": 'high',
        "alert": 'Gabapentin: reduce dose if eGFR<60 - sedation/encephalopathy risk if accumulated',
        "rationale": 'Entirely renally eliminated; standard doses accumulate in CKD causing sedation, myoclonus, or encephalopathy. Source: Lexicomp renal dosing.',
    },
    {
        "drug_terms": {'pregabid', 'pregabalin', 'pregeb'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_below_60',
        "action": 'reduce_dose',
        "urgency": 'high',
        "alert": 'Pregabalin: reduce dose if eGFR<60 - sedation/toxicity risk if accumulated',
        "rationale": 'Almost entirely renally cleared; requires dose reduction proportional to eGFR to avoid CNS toxicity/sedation. Source: Lexicomp renal dosing.',
    },
    {
        "drug_terms": {'ultracet', 'tramadol', 'tramazac'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_below_30',
        "action": 'reduce_dose',
        "urgency": 'medium',
        "alert": 'Tramadol: reduce dose/extend interval if eGFR<30 - seizure/sedation risk',
        "rationale": 'Active metabolite accumulates in renal impairment, increasing risk of seizures and CNS/respiratory depression; extend dosing interval in severe CKD. Source: Lexicomp renal dosing.',
    },
    {
        "drug_terms": {'codeine'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'avoid_below_30',
        "action": 'avoid',
        "urgency": 'high',
        "alert": 'Codeine: avoid/use with extreme caution if eGFR<30 - metabolite accumulation, resp depression',
        "rationale": 'Active metabolites (morphine-6-glucuronide) accumulate in renal failure causing prolonged sedation and respiratory depression. Source: Lexicomp renal dosing.',
    },
    {
        "drug_terms": {'zyloric', 'allopurinol'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_any_renal_impairment',
        "action": 'reduce_dose',
        "urgency": 'medium',
        "alert": 'Allopurinol: reduce starting dose in CKD; titrate to lowest effective dose',
        "rationale": 'Active metabolite oxypurinol accumulates in renal impairment; lower starting doses reduce risk of hypersensitivity syndrome and toxicity. Source: American College of Rheumatology gout guideline.',
    },
    {
        "drug_terms": {'colchicine', 'colchicum'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'avoid_below_30_reduce_dose_30_to_60',
        "action": 'avoid',
        "urgency": 'critical',
        "alert": 'Colchicine: avoid if eGFR<30; reduce dose 30-60 - myotoxicity/marrow toxicity risk',
        "rationale": 'Renally cleared with narrow therapeutic index; accumulation in CKD causes myopathy, neuropathy and bone marrow suppression, more severe with P-gp/CYP3A4 inhibitor co-use. Source: Lexicomp renal dosing / ACR gout guideline.',
    },
    {
        "drug_terms": {'acivir', 'zovirax', 'acyclovir', 'aciclovir'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_below_50',
        "action": 'reduce_dose',
        "urgency": 'high',
        "alert": 'Acyclovir: reduce dose/frequency if eGFR<50 - neurotoxicity/crystal nephropathy risk',
        "rationale": 'Renally excreted; accumulation in CKD causes neurotoxicity and crystal nephropathy, especially with IV or high oral doses and inadequate hydration. Source: Lexicomp renal dosing.',
    },
    {
        "drug_terms": {'famvir', 'famciclovir'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_below_60',
        "action": 'reduce_dose',
        "urgency": 'medium',
        "alert": 'Famciclovir: reduce dose/frequency if eGFR<60',
        "rationale": 'Active metabolite penciclovir is renally cleared; dose/interval adjustment required across CKD stages 3-5. Source: Lexicomp renal dosing.',
    },
    {
        "drug_terms": {'viraday', 'tenvir', 'tdf', 'tenofovir'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'avoid_below_50_or_reduce_interval',
        "action": 'avoid',
        "urgency": 'high',
        "alert": 'Tenofovir DF: avoid if CrCl<50 unless essential; extend dosing interval, monitor renal fn',
        "rationale": 'TDF is associated with proximal tubulopathy and progressive renal impairment; dose interval must be extended below CrCl 50 and use with caution/switch to TAF where possible. Source: FDA label (accessdata.fda.gov, tenofovir DF PI).',
    },
    {
        "drug_terms": {'zocon', 'forcan', 'fluconazole'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_below_50',
        "action": 'reduce_dose',
        "urgency": 'medium',
        "alert": 'Fluconazole: reduce dose 50% if eGFR<50 (CrCl<50 mL/min) after normal loading dose',
        "rationale": 'Predominantly renally excreted unchanged; maintenance dose should be halved below CrCl 50 mL/min following a standard loading dose. Source: Lexicomp renal dosing.',
    },
    {
        "drug_terms": {'istavel', 'januvia', 'sitagliptin'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_below_45',
        "action": 'reduce_dose',
        "urgency": 'medium',
        "alert": 'Sitagliptin: reduce dose if eGFR<45 (50mg if 30-45, 25mg if <30)',
        "rationale": 'Predominantly renally eliminated DPP-4 inhibitor; dose reduction required in moderate-severe CKD per manufacturer renal dosing table. Source: Drugs.com/Januvia prescribing information.',
    },
    {
        "drug_terms": {'jalra', 'vildagliptin', 'galvus'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_below_50',
        "action": 'reduce_dose',
        "urgency": 'medium',
        "alert": 'Vildagliptin: reduce dose to 50mg once daily if eGFR<50',
        "rationale": 'Renally cleared DPP-4 inhibitor; half-dose recommended in moderate-to-severe renal impairment and ESRD/dialysis. Source: PMC3639752 (vildagliptin in renal impairment).',
    },
    {
        "drug_terms": {'dapagliflozin', 'forxiga'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'avoid_below_25_reduced_glycemic_efficacy_below_45',
        "action": 'use_with_caution',
        "urgency": 'medium',
        "alert": 'Dapagliflozin: reduced glucose-lowering effect below eGFR 45; do not start if eGFR<25',
        "rationale": 'Glycemic efficacy declines as eGFR falls; current labeling still permits use for renal/CV protection at lower eGFR but glucose-lowering benefit is minimal below 45 and initiation is not recommended below 25. Source: AstraZeneca SGLT2i eGFR dosing chart.',
    },
    {
        "drug_terms": {'jardiance', 'empagliflozin'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'avoid_below_20_reduced_glycemic_efficacy_below_45',
        "action": 'use_with_caution',
        "urgency": 'medium',
        "alert": 'Empagliflozin: reduced glucose-lowering effect below eGFR 45; avoid initiation if eGFR<20',
        "rationale": 'Glycemic efficacy declines as eGFR falls; can be continued at low eGFR for kidney/CV protection per EMPA-KIDNEY data but glucose benefit is minimal below 45. Source: EMPA-KIDNEY trial (Clin Kidney J 2023) / StatPearls empagliflozin.',
    },
    {
        "drug_terms": {'insulin', 'actrapid', 'aspart', 'humalog', 'mixtard', 'lantus', 'human mixtard', 'glargine', 'novorapid'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'any_renal_impairment',
        "action": 'monitor_closely',
        "urgency": 'high',
        "alert": 'Insulin: reduce dose as eGFR falls - reduced renal insulin clearance raises hypoglycemia risk',
        "rationale": 'Kidneys metabolize/clear a significant fraction of circulating insulin; as CKD progresses insulin requirements typically fall and hypoglycemia risk rises without dose reduction. Source: KDIGO 2022 CKD guideline / AJKD Core Curriculum 2022.',
    },
    {
        "drug_terms": {'glyburide', 'euglucon', 'glibenclamide', 'daonil'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'avoid_any_renal_impairment',
        "action": 'avoid',
        "urgency": 'critical',
        "alert": 'Glibenclamide: avoid in CKD - active metabolites accumulate, high prolonged hypoglycemia risk',
        "rationale": 'Active metabolites are renally excreted and accumulate in CKD, causing prolonged, severe hypoglycemia; regulatory advisories recommend avoiding in renal impairment and the elderly. Source: HSA Singapore Safety Alert.',
    },
    {
        "drug_terms": {'glimy', 'glimepiride', 'amaryl'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'avoid_below_30_use_with_caution_30_to_60',
        "action": 'use_with_caution',
        "urgency": 'high',
        "alert": 'Glimepiride: use lowest dose with caution if eGFR 30-60; avoid if eGFR<30 - hypoglycemia risk',
        "rationale": 'Active metabolites are renally cleared and accumulate in CKD, increasing hypoglycemia risk; avoid in severe impairment and start at lowest dose in moderate CKD. Source: AJKD Core Curriculum 2022 (diabetes management in CKD).',
    },
    {
        "drug_terms": {'licab', 'lithium'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_any_renal_impairment_monitor_levels',
        "action": 'monitor_closely',
        "urgency": 'high',
        "alert": 'Lithium: narrow therapeutic index - reduce dose + monitor levels closely in CKD',
        "rationale": 'Almost entirely renally excreted with a narrow therapeutic window; CKD reduces clearance and raises toxicity risk, and lithium itself can cause nephrogenic diabetes insipidus and chronic tubulointerstitial damage. Source: Psychiatric Times/Int J Bipolar Disord CKD-lithium review.',
    },
    {
        "drug_terms": {'clarimac', 'claribid', 'clarithromycin'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'reduce_dose_below_30',
        "action": 'reduce_dose',
        "urgency": 'medium',
        "alert": 'Clarithromycin: reduce dose 50% if eGFR<30',
        "rationale": 'Renally eliminated macrolide; dose reduction recommended in severe renal impairment to avoid accumulation and QT-prolongation risk. Source: Lexicomp renal dosing.',
    },
    {
        "drug_terms": {'azee', 'azithral', 'azithromycin'},
        "trigger_diagnoses": {'nephropathy', 'chronic kidney disease', 'creatinine high', 'creatinine elevated', 'renal failure', 'renal impairment', 'egfr', 'ckd'},
        "egfr_threshold": 'no_adjustment_needed_use_with_caution_egfr_below_10',
        "action": 'use_with_caution',
        "urgency": 'medium',
        "alert": 'Azithromycin: generally no dose adjustment needed; use with caution if eGFR<10',
        "rationale": 'Primarily hepatically eliminated with minimal renal clearance; standard doses are usually safe across most CKD stages, with caution advised only in severe impairment. Source: Lexicomp renal dosing.',
    },
]
