import { useRef } from 'react';
import { useReactToPrint } from 'react-to-print';
import type { ProcessClinicalResponse } from '../types/clinical';

interface Props {
  results: ProcessClinicalResponse;
  patientName?: string;
  doctorName?: string;
  sessionId: string;
}

export default function PrintableReport({ results, patientName, doctorName, sessionId }: Props) {
  const reportRef = useRef<HTMLDivElement>(null);

  const handlePrint = useReactToPrint({
    contentRef: reportRef,
    documentTitle: `Clinical_Report_${patientName ?? 'Patient'}_${new Date().toLocaleDateString()}`,
  });

  const { soap, cds, facts } = results;
  const today = new Date().toLocaleString('en-IN', {
    dateStyle: 'full',
    timeStyle: 'short',
  });

  return (
    <>
      {/* Print Button */}
      <button
        onClick={handlePrint}
        className="flex items-center gap-1.5 text-xs font-medium text-slate-600 hover:text-slate-900 border border-slate-200 hover:border-slate-400 rounded px-3 py-1.5 transition-all"
        title="Export as PDF"
      >
        <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
        </svg>
        Export PDF
      </button>

      {/* Hidden Printable Report */}
      <div className="hidden">
        <div ref={reportRef} style={{ fontFamily: 'Georgia, serif', padding: '40px', maxWidth: '800px', margin: '0 auto' }}>
          {/* Header */}
          <div style={{ borderBottom: '2px solid #1e293b', paddingBottom: '16px', marginBottom: '24px' }}>
            <h1 style={{ fontSize: '24px', fontWeight: 'bold', color: '#0f172a', margin: 0 }}>
              Clinical Consultation Report
            </h1>
            <p style={{ fontSize: '13px', color: '#64748b', marginTop: '4px' }}>Generated by Clinical Copilot AI</p>
            <div style={{ marginTop: '16px', display: 'flex', justifyContent: 'space-between', fontSize: '13px', color: '#334155' }}>
              <div>
                <p><strong>Patient:</strong> {patientName ?? 'Anonymous Patient'}</p>
                {doctorName && <p><strong>Physician:</strong> Dr. {doctorName}</p>}
              </div>
              <div style={{ textAlign: 'right' }}>
                <p><strong>Date:</strong> {today}</p>
                <p style={{ fontSize: '11px', color: '#94a3b8' }}>Session: {sessionId}</p>
              </div>
            </div>
          </div>

          {/* SOAP Note */}
          <section style={{ marginBottom: '28px' }}>
            <h2 style={{ fontSize: '16px', fontWeight: 'bold', color: '#0f172a', marginBottom: '16px', borderLeft: '4px solid #1e293b', paddingLeft: '10px' }}>
              SOAP Note
            </h2>
            {[
              { label: 'S — Subjective', value: soap.S },
              { label: 'O — Objective', value: soap.O },
              { label: 'A — Assessment', value: soap.A },
              { label: 'P — Plan', value: soap.P },
            ].map(({ label, value }) => (
              <div key={label} style={{ marginBottom: '16px' }}>
                <p style={{ fontSize: '13px', fontWeight: 'bold', color: '#1e293b', marginBottom: '4px' }}>{label}</p>
                <p style={{ fontSize: '13px', color: '#334155', lineHeight: '1.6', margin: 0, whiteSpace: 'pre-wrap' }}>{value || '—'}</p>
              </div>
            ))}
          </section>

          {/* Clinical Facts */}
          {facts && (
            <section style={{ marginBottom: '28px' }}>
              <h2 style={{ fontSize: '16px', fontWeight: 'bold', color: '#0f172a', marginBottom: '16px', borderLeft: '4px solid #1e293b', paddingLeft: '10px' }}>
                Extracted Clinical Data
              </h2>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
                <tbody>
                  {facts.symptoms?.length > 0 && (
                    <tr style={{ borderBottom: '1px solid #e2e8f0' }}>
                      <td style={{ padding: '8px 0', fontWeight: 'bold', color: '#1e293b', width: '140px', verticalAlign: 'top' }}>Symptoms</td>
                      <td style={{ padding: '8px 0', color: '#334155' }}>{facts.symptoms.join(', ')}</td>
                    </tr>
                  )}
                  {facts.vitals?.length > 0 && (
                    <tr style={{ borderBottom: '1px solid #e2e8f0' }}>
                      <td style={{ padding: '8px 0', fontWeight: 'bold', color: '#1e293b', verticalAlign: 'top' }}>Vitals</td>
                      <td style={{ padding: '8px 0', color: '#334155' }}>{facts.vitals.join(', ')}</td>
                    </tr>
                  )}
                  {facts.allergies?.length > 0 && (
                    <tr style={{ borderBottom: '1px solid #e2e8f0' }}>
                      <td style={{ padding: '8px 0', fontWeight: 'bold', color: '#1e293b', verticalAlign: 'top' }}>Allergies</td>
                      <td style={{ padding: '8px 0', color: '#e11d48' }}>{facts.allergies.join(', ')}</td>
                    </tr>
                  )}
                  {facts.medications?.length > 0 && (
                    <tr style={{ borderBottom: '1px solid #e2e8f0' }}>
                      <td style={{ padding: '8px 0', fontWeight: 'bold', color: '#1e293b', verticalAlign: 'top' }}>Medications</td>
                      <td style={{ padding: '8px 0', color: '#334155' }}>
                        {facts.medications.map((m: { name: string; dosage: string; frequency: string }) =>
                          `${m.name} ${m.dosage} (${m.frequency})`
                        ).join(', ')}
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </section>
          )}

          {/* CDS Alerts */}
          {cds && cds.length > 0 && (
            <section style={{ marginBottom: '28px' }}>
              <h2 style={{ fontSize: '16px', fontWeight: 'bold', color: '#0f172a', marginBottom: '16px', borderLeft: '4px solid #dc2626', paddingLeft: '10px' }}>
                Clinical Decision Alerts
              </h2>
              {cds.map((alert, i) => (
                <div key={i} style={{ backgroundColor: '#fef2f2', border: '1px solid #fecaca', borderRadius: '6px', padding: '12px', marginBottom: '8px' }}>
                  <p style={{ fontSize: '13px', fontWeight: 'bold', color: '#991b1b', margin: '0 0 4px 0' }}>
                    [{alert.urgency?.toUpperCase()}] {alert.suggestion}
                  </p>
                  <p style={{ fontSize: '12px', color: '#7f1d1d', margin: 0 }}>{alert.rationale}</p>
                </div>
              ))}
            </section>
          )}

          {/* Footer */}
          <div style={{ borderTop: '1px solid #e2e8f0', paddingTop: '16px', fontSize: '11px', color: '#94a3b8', textAlign: 'center' }}>
            <p>⚠️ This report was AI-generated and must be reviewed by a licensed physician before acting on it.</p>
            <p>SHRUTI Health · Local clinical extraction + Sarvam ASR · Physician review required</p>
          </div>
        </div>
      </div>
    </>
  );
}
