"""ICD-10 code lookup for common Indian clinical diagnoses."""

# Maps canonical diagnosis name (lowercase) → ICD-10 code
_ICD10: dict[str, str] = {
    # Cardiovascular
    "ischemic heart disease": "I25.9",
    "coronary artery disease": "I25.9",
    "cad": "I25.9",
    "ihd": "I25.9",
    "acute myocardial infarction": "I21.9",
    "stemi": "I21.0",
    "nstemi": "I21.4",
    "unstable angina": "I20.0",
    "stable angina": "I20.8",
    "heart failure": "I50.9",
    "congestive heart failure": "I50.0",
    "chf": "I50.0",
    "left ventricular failure": "I50.1",
    "hypertension": "I10",
    "essential hypertension": "I10",
    "pulmonary hypertension": "I27.0",
    "atrial fibrillation": "I48.0",
    "af": "I48.0",
    "atrial flutter": "I48.3",
    "ventricular tachycardia": "I47.2",
    "vt": "I47.2",
    "svt": "I47.1",
    "heart block": "I44.2",
    "bundle branch block": "I45.4",
    "lbbb": "I44.7",
    "rbbb": "I45.1",
    "dilated cardiomyopathy": "I42.0",
    "hypertrophic cardiomyopathy": "I42.1",
    "cardiomyopathy": "I42.9",
    "mitral stenosis": "I05.0",
    "mitral regurgitation": "I34.0",
    "aortic stenosis": "I35.0",
    "aortic regurgitation": "I35.1",
    "tricuspid regurgitation": "I36.1",
    "rheumatic heart disease": "I09.9",
    "pericarditis": "I30.9",
    "pericardial effusion": "I31.3",
    "deep vein thrombosis": "I82.9",
    "dvt": "I82.9",
    "pulmonary embolism": "I26.9",
    "pe": "I26.9",
    "peripheral vascular disease": "I73.9",
    "pvd": "I73.9",
    "aortic aneurysm": "I71.9",
    # Endocrine / Metabolic
    "type 2 diabetes mellitus": "E11.9",
    "type 2 dm": "E11.9",
    "t2dm": "E11.9",
    "type 1 diabetes mellitus": "E10.9",
    "type 1 dm": "E10.9",
    "t1dm": "E10.9",
    "diabetes mellitus": "E14.9",
    "diabetes mellitus (uncontrolled)": "E11.65",
    "gestational diabetes": "O24.9",
    "hypothyroidism": "E03.9",
    "hyperthyroidism": "E05.9",
    "thyrotoxicosis": "E05.9",
    "goitre": "E04.9",
    "obesity": "E66.9",
    "dyslipidemia": "E78.5",
    "hypercholesterolemia": "E78.0",
    "hypertriglyceridemia": "E78.1",
    "metabolic syndrome": "E88.81",
    "hyperuricemia": "E79.0",
    "gout": "M10.9",
    "cushing syndrome": "E24.9",
    "addison disease": "E27.1",
    "hyperparathyroidism": "E21.0",
    "hypoparathyroidism": "E20.9",
    # Respiratory
    "asthma": "J45.9",
    "copd": "J44.9",
    "chronic obstructive pulmonary disease": "J44.9",
    "pneumonia": "J18.9",
    "community acquired pneumonia": "J18.9",
    "cap": "J18.9",
    "tuberculosis": "A15.9",
    "tb": "A15.9",
    "pulmonary tuberculosis": "A15.0",
    "bronchiectasis": "J47",
    "pleural effusion": "J90",
    "pneumothorax": "J93.9",
    "interstitial lung disease": "J84.9",
    "ild": "J84.9",
    "obstructive sleep apnea": "G47.33",
    "osa": "G47.33",
    "covid-19": "U07.1",
    "covid": "U07.1",
    "lung cancer": "C34.9",
    # Neurology
    "stroke": "I63.9",
    "ischemic stroke": "I63.9",
    "hemorrhagic stroke": "I61.9",
    "tia": "G45.9",
    "transient ischemic attack": "G45.9",
    "epilepsy": "G40.9",
    "seizures": "G40.9",
    "migraine": "G43.9",
    "tension headache": "G44.2",
    "parkinson's disease": "G20",
    "parkinsonism": "G20",
    "alzheimer's disease": "G30.9",
    "dementia": "F03",
    "multiple sclerosis": "G35",
    "ms": "G35",
    "peripheral neuropathy": "G62.9",
    "guillain barre syndrome": "G61.0",
    "meningitis": "G03.9",
    "encephalitis": "G04.9",
    "bell's palsy": "G51.0",
    "carpal tunnel syndrome": "G56.0",
    # Gastroenterology
    "gerd": "K21.0",
    "gastroesophageal reflux disease": "K21.0",
    "peptic ulcer": "K27.9",
    "gastric ulcer": "K25.9",
    "duodenal ulcer": "K26.9",
    "inflammatory bowel disease": "K51.9",
    "ibd": "K51.9",
    "ulcerative colitis": "K51.9",
    "crohn's disease": "K50.9",
    "irritable bowel syndrome": "K58.9",
    "ibs": "K58.9",
    "liver cirrhosis": "K74.6",
    "cirrhosis": "K74.6",
    "hepatitis a": "B15.9",
    "hepatitis b": "B18.1",
    "hepatitis c": "B18.2",
    "fatty liver": "K76.0",
    "nafld": "K76.0",
    "pancreatitis": "K85.9",
    "chronic pancreatitis": "K86.1",
    "cholecystitis": "K81.9",
    "cholelithiasis": "K80.20",
    "gallstones": "K80.20",
    "appendicitis": "K37",
    "celiac disease": "K90.0",
    # Nephrology
    "chronic kidney disease": "N18.9",
    "ckd": "N18.9",
    "acute kidney injury": "N17.9",
    "aki": "N17.9",
    "nephrotic syndrome": "N04.9",
    "nephrolithiasis": "N20.0",
    "kidney stones": "N20.0",
    "urinary tract infection": "N39.0",
    "uti": "N39.0",
    "glomerulonephritis": "N05.9",
    "polycystic kidney disease": "Q61.3",
    "pkd": "Q61.3",
    # Rheumatology / Musculoskeletal
    "rheumatoid arthritis": "M06.9",
    "ra": "M06.9",
    "osteoarthritis": "M19.9",
    "oa": "M19.9",
    "ankylosing spondylitis": "M45",
    "systemic lupus erythematosus": "M32.9",
    "sle": "M32.9",
    "lupus": "M32.9",
    "osteoporosis": "M81.0",
    "fibromyalgia": "M79.7",
    "low back pain": "M54.5",
    "cervical spondylosis": "M47.812",
    "frozen shoulder": "M75.0",
    # Hematology / Oncology
    "anemia": "D64.9",
    "iron deficiency anemia": "D50.9",
    "vitamin b12 deficiency": "D51.9",
    "sickle cell disease": "D57.1",
    "thalassemia": "D56.9",
    "leukemia": "C95.9",
    "lymphoma": "C85.9",
    "breast cancer": "C50.9",
    "lung cancer": "C34.9",
    "colon cancer": "C18.9",
    "cervical cancer": "C53.9",
    "prostate cancer": "C61",
    "oral cancer": "C06.9",
    "thrombocytopenia": "D69.6",
    # Infectious diseases
    "dengue": "A90",
    "dengue fever": "A90",
    "malaria": "B54",
    "typhoid": "A01.0",
    "typhoid fever": "A01.0",
    "chikungunya": "A92.0",
    "leptospirosis": "A27.9",
    "hiv": "B20",
    "aids": "B20",
    "sepsis": "A41.9",
    "urinary tract infection": "N39.0",
    # Psychiatry
    "depression": "F32.9",
    "major depressive disorder": "F32.9",
    "anxiety": "F41.9",
    "generalized anxiety disorder": "F41.1",
    "panic disorder": "F41.0",
    "schizophrenia": "F20.9",
    "bipolar disorder": "F31.9",
    "ocd": "F42.9",
    "ptsd": "F43.1",
    "insomnia": "G47.00",
    "adhd": "F90.9",
    # Dermatology
    "psoriasis": "L40.9",
    "eczema": "L30.9",
    "atopic dermatitis": "L20.9",
    "urticaria": "L50.9",
    "acne": "L70.9",
    "scabies": "B86",
    "fungal infection": "B35.9",
    "tinea": "B35.9",
    "vitiligo": "L80",
    # Obstetrics / Gynaecology
    "pcos": "E28.2",
    "polycystic ovary syndrome": "E28.2",
    "endometriosis": "N80.9",
    "uterine fibroids": "D25.9",
    "preeclampsia": "O14.9",
    "gestational hypertension": "O13",
}


def get_icd10(diagnosis: str) -> str | None:
    """Return ICD-10 code for a diagnosis name, case-insensitive. Returns None if unknown."""
    return _ICD10.get(diagnosis.lower().strip())


def annotate_diagnoses(diagnoses: list) -> list[dict]:
    """
    Convert a list of diagnosis strings into dicts with ICD-10 codes attached.
    Safe to call on any list — unknown diagnoses get code=None.
    """
    result = []
    for dx in diagnoses:
        name = str(dx).strip()
        result.append({
            "name": name,
            "icd10": get_icd10(name),
        })
    return result
