"""
ICD-10 code lookup for diagnoses extracted by the clinical pipeline.

Lookup is purely static — no generative model. Keys are normalised lowercase
diagnosis strings as produced by clinical_extractor.py's _DIAGNOSIS_MAP.
Values are (code, display) tuples per WHO ICD-10 2019 revision.

Common Indian OPD diagnoses are prioritised. Add entries as new diagnoses
are confirmed in production transcripts.
"""

_ICD10: dict[str, tuple[str, str]] = {
    # ── Infectious ────────────────────────────────────────────────────────────
    "acute upper respiratory tract infection": ("J06.9", "Acute upper respiratory infection, unspecified"),
    "upper respiratory tract infection": ("J06.9", "Acute upper respiratory infection, unspecified"),
    "urti": ("J06.9", "Acute upper respiratory infection, unspecified"),
    "viral pharyngitis": ("J02.9", "Acute pharyngitis, unspecified"),
    "acute pharyngitis": ("J02.9", "Acute pharyngitis, unspecified"),
    "tonsillitis": ("J03.9", "Acute tonsillitis, unspecified"),
    "acute tonsillitis": ("J03.9", "Acute tonsillitis, unspecified"),
    "peritonsillar abscess": ("J36", "Peritonsillar abscess"),
    "laryngitis": ("J04.0", "Acute laryngitis"),
    "tracheitis": ("J04.1", "Acute tracheitis"),
    "croup": ("J05.0", "Acute obstructive laryngitis [croup]"),
    "acute bronchitis": ("J20.9", "Acute bronchitis, unspecified"),
    "bronchiolitis": ("J21.9", "Acute bronchiolitis, unspecified"),
    "pneumonia": ("J18.9", "Pneumonia, unspecified organism"),
    "community acquired pneumonia": ("J18.9", "Pneumonia, unspecified organism"),
    "atypical pneumonia": ("J18.9", "Pneumonia, unspecified organism"),
    "pleural effusion": ("J90", "Pleural effusion, not elsewhere classified"),
    "typhoid fever": ("A01.0", "Typhoid fever"),
    "enteric fever": ("A01.0", "Typhoid fever"),
    "dengue fever": ("A97.9", "Dengue fever, unspecified"),
    "dengue": ("A97.9", "Dengue fever, unspecified"),
    "dengue hemorrhagic fever": ("A97.1", "Dengue haemorrhagic fever"),
    "malaria": ("B54", "Unspecified malaria"),
    "falciparum malaria": ("B50.9", "Plasmodium falciparum malaria, unspecified"),
    "vivax malaria": ("B51.9", "Plasmodium vivax malaria without complication"),
    "tuberculosis": ("A15.9", "Respiratory tuberculosis, unspecified"),
    "pulmonary tuberculosis": ("A15.0", "Tuberculosis of lung"),
    "extrapulmonary tuberculosis": ("A19.9", "Miliary tuberculosis, unspecified"),
    "urinary tract infection": ("N39.0", "Urinary tract infection, site not specified"),
    "uti": ("N39.0", "Urinary tract infection, site not specified"),
    "gastroenteritis": ("A09", "Other and unspecified gastroenteritis and colitis"),
    "acute gastroenteritis": ("A09", "Other and unspecified gastroenteritis and colitis"),
    "viral gastroenteritis": ("A08.4", "Viral intestinal infection, unspecified"),
    "food poisoning": ("A05.9", "Bacterial foodborne intoxication, unspecified"),
    "cholera": ("A00.9", "Cholera, unspecified"),
    "leptospirosis": ("A27.9", "Leptospirosis, unspecified"),
    "chickenpox": ("B01.9", "Varicella without complication"),
    "varicella": ("B01.9", "Varicella without complication"),
    "herpes zoster": ("B02.9", "Zoster without complication"),
    "shingles": ("B02.9", "Zoster without complication"),
    "measles": ("B05.9", "Measles without complication"),
    "mumps": ("B26.9", "Mumps without complication"),
    "hepatitis a": ("B15.9", "Hepatitis A without hepatic coma"),
    "hepatitis b": ("B16.9", "Acute hepatitis B without delta-agent and without hepatic coma"),
    "hepatitis c": ("B17.1", "Acute hepatitis C"),
    "viral hepatitis": ("B19.9", "Unspecified viral hepatitis without hepatic coma"),
    "jaundice": ("R17", "Unspecified jaundice"),
    "cellulitis": ("L03.90", "Cellulitis, unspecified"),
    "abscess": ("L02.91", "Cutaneous abscess, unspecified"),
    "impetigo": ("L01.00", "Impetigo, unspecified"),
    "scabies": ("B86", "Scabies"),
    "tinea corporis": ("B35.4", "Tinea corporis"),
    "ringworm": ("B35.4", "Tinea corporis"),
    "tinea pedis": ("B35.3", "Tinea pedis"),
    "athlete's foot": ("B35.3", "Tinea pedis"),
    "tinea capitis": ("B35.0", "Tinea barbae and tinea capitis"),
    "onychomycosis": ("B35.1", "Tinea unguium"),
    "fungal nail infection": ("B35.1", "Tinea unguium"),
    "meningitis": ("G03.9", "Meningitis, unspecified"),
    "bacterial meningitis": ("G00.9", "Bacterial meningitis, unspecified"),
    "sepsis": ("A41.9", "Sepsis, unspecified organism"),
    "covid-19": ("U07.1", "COVID-19"),
    "covid": ("U07.1", "COVID-19"),
    "influenza": ("J11.1", "Influenza with other respiratory manifestations, virus not identified"),

    # ── Cardiovascular ────────────────────────────────────────────────────────
    "hypertension": ("I10", "Essential (primary) hypertension"),
    "essential hypertension": ("I10", "Essential (primary) hypertension"),
    "stage 1 hypertension": ("I10", "Essential (primary) hypertension"),
    "stage 2 hypertension": ("I10", "Essential (primary) hypertension"),
    "coronary artery disease": ("I25.10", "Atherosclerotic heart disease of native coronary artery without angina pectoris"),
    "ischemic heart disease": ("I25.9", "Chronic ischaemic heart disease, unspecified"),
    "heart failure": ("I50.9", "Heart failure, unspecified"),
    "congestive heart failure": ("I50.0", "Congestive heart failure"),
    "atrial fibrillation": ("I48.91", "Unspecified atrial fibrillation"),
    "angina": ("I20.9", "Angina pectoris, unspecified"),
    "unstable angina": ("I20.0", "Unstable angina"),
    "myocardial infarction": ("I21.9", "Acute myocardial infarction, unspecified"),
    "heart attack": ("I21.9", "Acute myocardial infarction, unspecified"),
    "deep vein thrombosis": ("I82.409", "Acute embolism and thrombosis of unspecified deep veins of unspecified lower extremity"),
    "dvt": ("I82.409", "Acute embolism and thrombosis of unspecified deep veins of unspecified lower extremity"),
    "peripheral arterial disease": ("I73.9", "Peripheral vascular disease, unspecified"),
    "varicose veins": ("I83.90", "Varicose veins of unspecified lower extremity without ulcer or inflammation"),
    "pulmonary embolism": ("I26.99", "Other pulmonary embolism without acute cor pulmonale"),
    "aortic stenosis": ("I35.0", "Nonrheumatic aortic (valve) stenosis"),
    "mitral regurgitation": ("I34.0", "Nonrheumatic mitral (valve) insufficiency"),
    "cardiomyopathy": ("I42.9", "Cardiomyopathy, unspecified"),
    "rheumatic heart disease": ("I09.9", "Rheumatic heart disease, unspecified"),
    "pericarditis": ("I30.9", "Acute pericarditis, unspecified"),

    # ── Metabolic / Endocrine ─────────────────────────────────────────────────
    "diabetes mellitus": ("E11.9", "Type 2 diabetes mellitus without complications"),
    "diabetes mellitus type 2": ("E11.9", "Type 2 diabetes mellitus without complications"),
    "type 2 diabetes": ("E11.9", "Type 2 diabetes mellitus without complications"),
    "diabetes mellitus type 1": ("E10.9", "Type 1 diabetes mellitus without complications"),
    "type 1 diabetes": ("E10.9", "Type 1 diabetes mellitus without complications"),
    "diabetic nephropathy": ("E11.65", "Type 2 diabetes mellitus with hyperglycemia"),
    "diabetic neuropathy": ("E11.40", "Type 2 diabetes mellitus with diabetic neuropathy, unspecified"),
    "diabetic retinopathy": ("E11.319", "Type 2 diabetes mellitus with unspecified diabetic retinopathy without macular edema"),
    "hypoglycemia": ("E11.649", "Type 2 diabetes mellitus with hypoglycemia without coma"),
    "hyperglycemia": ("E11.65", "Type 2 diabetes mellitus with hyperglycemia"),
    "hypothyroidism": ("E03.9", "Hypothyroidism, unspecified"),
    "hyperthyroidism": ("E05.90", "Thyrotoxicosis, unspecified without thyrotoxic crisis"),
    "thyroid disorder": ("E07.9", "Disorder of thyroid, unspecified"),
    "goitre": ("E04.9", "Nontoxic goitre, unspecified"),
    "obesity": ("E66.9", "Obesity, unspecified"),
    "overweight": ("E66.9", "Obesity, unspecified"),
    "dyslipidemia": ("E78.5", "Hyperlipidemia, unspecified"),
    "hyperlipidemia": ("E78.5", "Hyperlipidemia, unspecified"),
    "hypercholesterolemia": ("E78.0", "Pure hypercholesterolaemia"),
    "hypertriglyceridemia": ("E78.1", "Pure hyperglyceridaemia"),
    "metabolic syndrome": ("E88.81", "Metabolic syndrome"),
    "hyperuricemia": ("E79.0", "Hyperuricaemia without signs of inflammatory arthritis and tophaceous disease"),
    "gout": ("M10.9", "Gout, unspecified"),
    "gout flare": ("M10.9", "Gout, unspecified"),
    "anemia": ("D64.9", "Anaemia, unspecified"),
    "iron deficiency anemia": ("D50.9", "Iron deficiency anaemia, unspecified"),
    "vitamin b12 deficiency": ("E53.8", "Deficiency of other specified B group vitamins"),
    "b12 deficiency": ("E53.8", "Deficiency of other specified B group vitamins"),
    "vitamin d deficiency": ("E55.9", "Vitamin D deficiency, unspecified"),
    "folate deficiency": ("E53.8", "Deficiency of other specified B group vitamins"),
    "adrenal insufficiency": ("E27.1", "Primary adrenocortical insufficiency"),
    "cushing's syndrome": ("E24.9", "Cushing's syndrome, unspecified"),

    # ── Respiratory ───────────────────────────────────────────────────────────
    "asthma": ("J45.909", "Unspecified asthma, uncomplicated"),
    "bronchial asthma": ("J45.909", "Unspecified asthma, uncomplicated"),
    "acute asthma": ("J45.901", "Unspecified asthma with (acute) exacerbation"),
    "copd": ("J44.1", "Chronic obstructive pulmonary disease with acute exacerbation"),
    "chronic obstructive pulmonary disease": ("J44.1", "Chronic obstructive pulmonary disease with acute exacerbation"),
    "allergic rhinitis": ("J30.9", "Allergic rhinitis, unspecified"),
    "sinusitis": ("J32.9", "Chronic sinusitis, unspecified"),
    "acute sinusitis": ("J01.90", "Acute sinusitis, unspecified"),
    "chronic sinusitis": ("J32.9", "Chronic sinusitis, unspecified"),
    "pulmonary fibrosis": ("J84.10", "Pulmonary fibrosis, unspecified"),
    "interstitial lung disease": ("J84.9", "Interstitial pulmonary disease, unspecified"),
    "sleep apnea": ("G47.30", "Sleep apnea, unspecified"),
    "obstructive sleep apnea": ("G47.33", "Obstructive sleep apnea (adult) (pediatric)"),
    "sarcoidosis": ("D86.9", "Sarcoidosis, unspecified"),
    "lung cancer": ("C34.90", "Malignant neoplasm of unspecified part of unspecified bronchus or lung"),

    # ── Gastrointestinal ─────────────────────────────────────────────────────
    "peptic ulcer disease": ("K27.9", "Peptic ulcer, unspecified, without haemorrhage or perforation"),
    "peptic ulcer": ("K27.9", "Peptic ulcer, unspecified, without haemorrhage or perforation"),
    "gastric ulcer": ("K25.9", "Gastric ulcer, unspecified as acute or chronic, without haemorrhage or perforation"),
    "duodenal ulcer": ("K26.9", "Duodenal ulcer, unspecified as acute or chronic, without haemorrhage or perforation"),
    "gastroesophageal reflux disease": ("K21.9", "Gastro-oesophageal reflux disease without oesophagitis"),
    "gerd": ("K21.9", "Gastro-oesophageal reflux disease without oesophagitis"),
    "acid reflux": ("K21.9", "Gastro-oesophageal reflux disease without oesophagitis"),
    "irritable bowel syndrome": ("K58.9", "Irritable bowel syndrome without diarrhoea"),
    "ibs": ("K58.9", "Irritable bowel syndrome without diarrhoea"),
    "constipation": ("K59.00", "Constipation, unspecified"),
    "chronic constipation": ("K59.04", "Chronic idiopathic constipation"),
    "liver cirrhosis": ("K74.60", "Unspecified cirrhosis of liver"),
    "fatty liver": ("K76.0", "Fatty (change of) liver, not elsewhere classified"),
    "non-alcoholic fatty liver disease": ("K76.0", "Fatty (change of) liver, not elsewhere classified"),
    "nafld": ("K76.0", "Fatty (change of) liver, not elsewhere classified"),
    "appendicitis": ("K37", "Unspecified appendicitis"),
    "acute appendicitis": ("K35.80", "Other and unspecified acute appendicitis without abscess"),
    "cholecystitis": ("K81.9", "Cholecystitis, unspecified"),
    "acute cholecystitis": ("K81.0", "Acute cholecystitis"),
    "cholelithiasis": ("K80.20", "Calculus of gallbladder without cholecystitis without obstruction"),
    "gallstones": ("K80.20", "Calculus of gallbladder without cholecystitis without obstruction"),
    "pancreatitis": ("K85.90", "Acute pancreatitis without necrosis or infection, unspecified"),
    "acute pancreatitis": ("K85.90", "Acute pancreatitis without necrosis or infection, unspecified"),
    "chronic pancreatitis": ("K86.1", "Other chronic pancreatitis"),
    "inflammatory bowel disease": ("K52.9", "Noninfective gastroenteritis and colitis, unspecified"),
    "crohn's disease": ("K50.90", "Crohn's disease of small intestine without complications"),
    "ulcerative colitis": ("K51.90", "Ulcerative colitis, unspecified, without complications"),
    "hemorrhoids": ("K64.9", "Unspecified haemorrhoids"),
    "piles": ("K64.9", "Unspecified haemorrhoids"),
    "anal fissure": ("K60.2", "Anal fissure, unspecified"),
    "intestinal obstruction": ("K56.60", "Unspecified intestinal obstruction"),
    "hernia": ("K46.9", "Unspecified abdominal hernia without obstruction or gangrene"),
    "inguinal hernia": ("K40.90", "Unilateral inguinal hernia, without obstruction or gangrene, not specified as recurrent"),
    "umbilical hernia": ("K42.9", "Umbilical hernia without obstruction or gangrene"),

    # ── Musculoskeletal ───────────────────────────────────────────────────────
    "osteoarthritis": ("M19.90", "Unspecified osteoarthritis, unspecified site"),
    "knee osteoarthritis": ("M17.9", "Gonarthrosis, unspecified"),
    "hip osteoarthritis": ("M16.9", "Coxarthrosis, unspecified"),
    "rheumatoid arthritis": ("M06.9", "Rheumatoid arthritis, unspecified"),
    "reactive arthritis": ("M02.9", "Reactive arthropathy, unspecified"),
    "back pain": ("M54.5", "Low back pain"),
    "low back pain": ("M54.5", "Low back pain"),
    "neck pain": ("M54.2", "Cervicalgia"),
    "cervical spondylosis": ("M47.812", "Spondylosis without myelopathy or radiculopathy, cervical region"),
    "lumbar spondylosis": ("M47.816", "Spondylosis without myelopathy or radiculopathy, lumbar region"),
    "lumbar disc prolapse": ("M51.16", "Intervertebral disc degeneration, lumbar region"),
    "sciatica": ("M54.4", "Lumbago with sciatica"),
    "osteoporosis": ("M81.0", "Age-related osteoporosis without current pathological fracture"),
    "fibromyalgia": ("M79.3", "Panniculitis"),
    "tendinitis": ("M77.9", "Enthesopathy, unspecified"),
    "rotator cuff syndrome": ("M75.1", "Rotator cuff syndrome"),
    "frozen shoulder": ("M75.0", "Adhesive capsulitis of shoulder"),
    "carpal tunnel syndrome": ("G56.00", "Carpal tunnel syndrome, unspecified upper limb"),
    "plantar fasciitis": ("M72.2", "Plantar fascial fibromatosis"),
    "lateral epicondylitis": ("M77.1", "Lateral epicondylitis"),
    "tennis elbow": ("M77.1", "Lateral epicondylitis"),
    "bursitis": ("M71.9", "Bursopathy, unspecified"),
    "fracture": ("T14.2", "Fracture of unspecified body region"),
    "joint pain": ("M25.50", "Pain in unspecified joint"),
    "arthralgia": ("M25.50", "Pain in unspecified joint"),

    # ── Neurological ─────────────────────────────────────────────────────────
    "migraine": ("G43.909", "Migraine, unspecified, not intractable, without status migrainosus"),
    "tension headache": ("G44.20", "Tension-type headache, unspecified, not intractable"),
    "cluster headache": ("G44.001", "Cluster headache syndrome, unspecified, intractable"),
    "epilepsy": ("G40.909", "Epilepsy, unspecified, not intractable, without status epilepticus"),
    "stroke": ("I63.9", "Cerebral infarction, unspecified"),
    "cerebrovascular accident": ("I63.9", "Cerebral infarction, unspecified"),
    "transient ischemic attack": ("G45.9", "Transient cerebral ischaemic attack, unspecified"),
    "tia": ("G45.9", "Transient cerebral ischaemic attack, unspecified"),
    "parkinson's disease": ("G20", "Parkinson's disease"),
    "alzheimer's disease": ("G30.9", "Alzheimer's disease, unspecified"),
    "peripheral neuropathy": ("G62.9", "Polyneuropathy, unspecified"),
    "bell's palsy": ("G51.0", "Bell's palsy"),
    "trigeminal neuralgia": ("G50.0", "Trigeminal neuralgia"),
    "essential tremor": ("G25.0", "Essential tremor"),
    "vertigo": ("H81.39", "Other peripheral vertigo, unspecified ear"),
    "bppv": ("H81.10", "Benign paroxysmal vertigo, unspecified ear"),
    "benign paroxysmal positional vertigo": ("H81.10", "Benign paroxysmal vertigo, unspecified ear"),
    "multiple sclerosis": ("G35", "Multiple sclerosis"),
    "mononeuropathy": ("G58.9", "Mononeuropathy, unspecified"),
    "guillain-barre syndrome": ("G61.0", "Guillain-Barré syndrome"),
    "febrile seizures": ("R56.00", "Simple febrile convulsions"),

    # ── Renal ─────────────────────────────────────────────────────────────────
    "chronic kidney disease": ("N18.9", "Chronic kidney disease, unspecified"),
    "ckd": ("N18.9", "Chronic kidney disease, unspecified"),
    "ckd stage 3": ("N18.3", "Chronic kidney disease, stage 3 (moderate)"),
    "ckd stage 4": ("N18.4", "Chronic kidney disease, stage 4 (severe)"),
    "ckd stage 5": ("N18.5", "Chronic kidney disease, stage 5"),
    "end stage renal disease": ("N18.6", "End stage renal disease"),
    "acute kidney injury": ("N17.9", "Acute kidney failure, unspecified"),
    "kidney stones": ("N20.0", "Calculus of kidney"),
    "nephrolithiasis": ("N20.0", "Calculus of kidney"),
    "renal colic": ("N23", "Unspecified renal colic"),
    "ureterolithiasis": ("N20.1", "Calculus of ureter"),
    "nephrotic syndrome": ("N04.9", "Nephrotic syndrome with unspecified morphological changes"),
    "glomerulonephritis": ("N05.9", "Unspecified nephritic syndrome with unspecified morphological changes"),
    "prostatitis": ("N41.9", "Inflammatory disease of prostate, unspecified"),
    "benign prostatic hyperplasia": ("N40.0", "Benign prostatic hyperplasia without lower urinary tract symptoms"),
    "bph": ("N40.0", "Benign prostatic hyperplasia without lower urinary tract symptoms"),
    "overactive bladder": ("N32.81", "Overactive bladder"),

    # ── Dermatological ────────────────────────────────────────────────────────
    "eczema": ("L30.9", "Dermatitis, unspecified"),
    "atopic dermatitis": ("L20.9", "Atopic dermatitis, unspecified"),
    "contact dermatitis": ("L25.9", "Unspecified contact dermatitis, unspecified cause"),
    "seborrheic dermatitis": ("L21.9", "Seborrhoeic dermatitis, unspecified"),
    "psoriasis": ("L40.9", "Psoriasis, unspecified"),
    "urticaria": ("L50.9", "Urticaria, unspecified"),
    "acne": ("L70.0", "Acne vulgaris"),
    "acne vulgaris": ("L70.0", "Acne vulgaris"),
    "rosacea": ("L71.9", "Rosacea, unspecified"),
    "vitiligo": ("L80", "Vitiligo"),
    "alopecia": ("L65.9", "Nonscarring hair loss, unspecified"),
    "alopecia areata": ("L63.9", "Alopecia areata, unspecified"),
    "fungal infection": ("B49", "Unspecified mycosis"),
    "candidiasis": ("B37.9", "Candidiasis, unspecified"),
    "wound infection": ("T14.0", "Open wound of unspecified body region"),
    "lipoma": ("D17.9", "Benign lipomatous neoplasm, unspecified"),
    "sebaceous cyst": ("L72.3", "Sebaceous cyst"),
    "herpes simplex": ("B00.9", "Herpesviral infection, unspecified"),

    # ── Mental Health ─────────────────────────────────────────────────────────
    "depression": ("F32.9", "Major depressive disorder, single episode, unspecified"),
    "major depressive disorder": ("F32.9", "Major depressive disorder, single episode, unspecified"),
    "anxiety": ("F41.9", "Anxiety disorder, unspecified"),
    "anxiety disorder": ("F41.9", "Anxiety disorder, unspecified"),
    "generalized anxiety disorder": ("F41.1", "Generalised anxiety disorder"),
    "panic disorder": ("F41.0", "Panic disorder [episodic paroxysmal anxiety]"),
    "ocd": ("F42.9", "Obsessive-compulsive disorder, unspecified"),
    "obsessive compulsive disorder": ("F42.9", "Obsessive-compulsive disorder, unspecified"),
    "ptsd": ("F43.10", "Post-traumatic stress disorder, unspecified"),
    "insomnia": ("G47.00", "Insomnia, unspecified"),
    "insomnia disorder": ("G47.00", "Insomnia, unspecified"),
    "schizophrenia": ("F20.9", "Schizophrenia, unspecified"),
    "bipolar disorder": ("F31.9", "Bipolar disorder, unspecified"),
    "attention deficit hyperactivity disorder": ("F90.9", "Attention-deficit hyperactivity disorder, unspecified type"),
    "adhd": ("F90.9", "Attention-deficit hyperactivity disorder, unspecified type"),
    "alcohol use disorder": ("F10.20", "Alcohol dependence, uncomplicated"),
    "substance use disorder": ("F19.90", "Other psychoactive substance use, unspecified, uncomplicated"),

    # ── Gynaecological / Obstetric ────────────────────────────────────────────
    "polycystic ovary syndrome": ("E28.2", "Polycystic ovarian syndrome"),
    "pcos": ("E28.2", "Polycystic ovarian syndrome"),
    "endometriosis": ("N80.9", "Endometriosis, unspecified"),
    "menorrhagia": ("N92.0", "Excessive and frequent menstruation with regular cycle"),
    "dysmenorrhea": ("N94.6", "Dysmenorrhoea, unspecified"),
    "amenorrhea": ("N91.2", "Amenorrhoea, unspecified"),
    "menopausal syndrome": ("N95.1", "Menopausal and female climacteric states"),
    "menopause": ("N95.1", "Menopausal and female climacteric states"),
    "pelvic inflammatory disease": ("N73.9", "Female pelvic inflammatory disease, unspecified"),
    "pid": ("N73.9", "Female pelvic inflammatory disease, unspecified"),
    "ovarian cyst": ("N83.20", "Unspecified ovarian cyst"),
    "vaginal discharge": ("N89.8", "Other specified noninflammatory disorders of vagina"),
    "cervical erosion": ("N86", "Erosion and ectropion of cervix uteri"),
    "fibroid uterus": ("D25.9", "Leiomyoma of uterus, unspecified"),
    "uterine fibroid": ("D25.9", "Leiomyoma of uterus, unspecified"),
    "preeclampsia": ("O14.90", "Unspecified pre-eclampsia, unspecified trimester"),
    "gestational diabetes": ("O24.419", "Gestational diabetes mellitus in pregnancy, unspecified control"),

    # ── ENT ──────────────────────────────────────────────────────────────────
    "otitis media": ("H66.90", "Otitis media, unspecified, unspecified ear"),
    "otitis externa": ("H60.90", "Unspecified otitis externa, unspecified ear"),
    "acute otitis media": ("H66.90", "Otitis media, unspecified, unspecified ear"),
    "chronic otitis media": ("H66.10", "Chronic tubotympanic suppurative otitis media, unspecified"),
    "tinnitus": ("H93.19", "Tinnitus, unspecified ear"),
    "sudden hearing loss": ("H91.20", "Sudden idiopathic hearing loss, unspecified ear"),
    "nasal polyp": ("J33.9", "Nasal polyp, unspecified"),
    "deviated nasal septum": ("J34.2", "Deviated nasal septum"),
    "epistaxis": ("R04.0", "Epistaxis"),
    "nosebleed": ("R04.0", "Epistaxis"),

    # ── Ophthalmological ─────────────────────────────────────────────────────
    "conjunctivitis": ("H10.9", "Unspecified conjunctivitis"),
    "allergic conjunctivitis": ("H10.10", "Unspecified acute atopic conjunctivitis"),
    "cataract": ("H26.9", "Unspecified cataract"),
    "glaucoma": ("H40.9", "Unspecified glaucoma"),
    "macular degeneration": ("H35.30", "Unspecified macular degeneration"),
    "diabetic retinopathy": ("E11.319", "Type 2 diabetes mellitus with unspecified diabetic retinopathy without macular edema"),
    "blepharitis": ("H01.009", "Unspecified blepharitis, unspecified eye, unspecified eyelid"),
    "chalazion": ("H00.19", "Chalazion, unspecified eyelid"),
    "stye": ("H00.019", "Hordeolum externum, unspecified eye, unspecified eyelid"),
    "dry eye": ("H04.123", "Dry eye syndrome of bilateral lacrimal glands"),
    "corneal ulcer": ("H16.009", "Unspecified corneal ulcer, unspecified eye"),
    "refractive error": ("H52.7", "Unspecified disorder of refraction"),
    "myopia": ("H52.10", "Myopia, unspecified"),
    "hypermetropia": ("H52.0", "Hypermetropia"),

    # ── Oncology (screening / common presentations) ────────────────────────
    "breast cancer": ("C50.911", "Malignant neoplasm of unspecified site of right female breast"),
    "cervical cancer": ("C53.9", "Malignant neoplasm of cervix uteri, unspecified"),
    "colorectal cancer": ("C18.9", "Malignant neoplasm of colon, unspecified"),
    "prostate cancer": ("C61", "Malignant neoplasm of prostate"),
    "oral cancer": ("C06.9", "Malignant neoplasm of mouth, unspecified"),
    "thyroid cancer": ("C73", "Malignant neoplasm of thyroid gland"),
    "lymphoma": ("C85.90", "Non-Hodgkin lymphoma, unspecified, unspecified site"),

    # ── Paediatric ────────────────────────────────────────────────────────────
    "febrile seizures": ("R56.00", "Simple febrile convulsions"),
    "failure to thrive": ("R62.51", "Failure to thrive (child)"),
    "developmental delay": ("F89", "Unspecified disorder of psychological development"),
    "acute otitis media with effusion": ("H65.90", "Unspecified nonsuppurative otitis media, unspecified ear"),
    "neonatal jaundice": ("P59.9", "Neonatal jaundice, unspecified"),
    "birth asphyxia": ("P21.9", "Birth asphyxia, unspecified"),

    # ── Surgical / Trauma ─────────────────────────────────────────────────────
    "laceration": ("S09.90XA", "Unspecified injury of head, initial encounter"),
    "burn": ("T30.0", "Burn of unspecified body region, unspecified degree"),
    "fracture limb": ("T14.2", "Fracture of unspecified body region"),
    "dislocation": ("T14.3", "Dislocation of joint of unspecified body region"),
    "sprain": ("T14.3", "Dislocation of joint of unspecified body region"),
    "head injury": ("S09.90XA", "Unspecified injury of head, initial encounter"),
    "concussion": ("S09.90XA", "Unspecified injury of head, initial encounter"),

    # ── Miscellaneous / General ────────────────────────────────────────────────
    "fever": ("R50.9", "Fever, unspecified"),
    "pyrexia": ("R50.9", "Fever, unspecified"),
    "dehydration": ("E86.0", "Dehydration"),
    "acute pain": ("R52", "Pain, unspecified"),
    "chronic pain": ("R52", "Pain, unspecified"),
    "fatigue": ("R53.83", "Other fatigue"),
    "chronic fatigue syndrome": ("G93.3", "Postviral fatigue syndrome"),
    "weight loss": ("R63.4", "Abnormal weight loss"),
    "weight gain": ("R63.5", "Abnormal weight gain"),
    "malnutrition": ("E46", "Unspecified protein-calorie malnutrition"),
    "vitamin deficiency": ("E56.9", "Vitamin deficiency, unspecified"),
    "dental caries": ("K02.9", "Dental caries, unspecified"),
    "periodontitis": ("K05.30", "Chronic periodontitis, unspecified"),
    "gingivitis": ("K05.10", "Chronic gingivitis, plaque induced"),
}


def lookup(diagnosis: str) -> dict | None:
    """Return {"code": "E11.9", "display": "...", "system": "ICD-10"} or None."""
    key = diagnosis.strip().lower()
    result = _ICD10.get(key)
    if result:
        return {"code": result[0], "display": result[1], "system": "ICD-10"}
    return None


def enrich_diagnoses(diagnoses: list[str]) -> list[dict]:
    """Convert plain-text diagnosis list to coded objects.

    Each item becomes:
      {"text": "Diabetes Mellitus", "code": "E11.9",
       "display": "Type 2 diabetes mellitus...", "system": "ICD-10"}
    or:
      {"text": "Some Unknown Dx"}   — when no code found.
    """
    enriched = []
    for dx in diagnoses:
        entry: dict = {"text": dx}
        coded = lookup(dx)
        if coded:
            entry.update(coded)
        enriched.append(entry)
    return enriched
