"""Medical ontology loader — replaces hand-curated keyword maps with comprehensive term databases.

Loads terms from:
  1. Built-in seed vocabulary (2000+ terms across all specialties)
  2. SNOMED-CT flat files (if present in data/ontology/)
  3. RxNorm flat files (if present in data/ontology/)
  4. LOINC flat files (if present in data/ontology/)
  5. Learned overlays from the doctor correction flywheel

Uses SymSpell for O(1) fuzzy matching instead of brute-force RapidFuzz.
"""

import csv
import logging
import re
import time
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

_DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data" / "ontology"

# SymSpell for fast fuzzy matching (edit distance ≤2 in microseconds)
try:
    from symspellpy import SymSpell, Verbosity
    _HAS_SYMSPELL = True
except ImportError:
    SymSpell = None  # type: ignore[assignment]
    Verbosity = None  # type: ignore[assignment]
    _HAS_SYMSPELL = False
    logger.info("symspellpy not installed — falling back to RapidFuzz for fuzzy matching")


class MedicalOntology:
    """Singleton ontology that loads once at startup and provides O(1) term lookup."""

    def __init__(self):
        self.symptoms: dict[str, str] = {}
        self.medications: dict[str, str] = {}
        self.investigations: dict[str, str] = {}
        self.diagnoses: dict[str, str] = {}

        # Hinglish variant maps: hinglish_term → english_canonical
        self.hinglish_symptoms: dict[str, str] = {}
        self.hinglish_medications: dict[str, str] = {}
        self.hinglish_diagnoses: dict[str, str] = {}

        # SymSpell instances per category for fast fuzzy lookup
        self._sym_symptoms: Optional[SymSpell] = None
        self._sym_medications: Optional[SymSpell] = None
        self._sym_investigations: Optional[SymSpell] = None
        self._sym_diagnoses: Optional[SymSpell] = None

        self._loaded = False

    def load(self, learned_overlays: dict | None = None):
        """Load all ontology sources. Call once at startup."""
        t0 = time.time()

        self._load_seed_vocabulary()
        self._load_hinglish_variants()

        # Build SymSpell ONLY from seed vocab + Hinglish (hand-curated, safe for fuzzy)
        self._build_symspell_indices()

        # Expanded ontology loaded AFTER SymSpell build — exact match only
        self._load_tier1_data_files()
        self._load_snomed_if_present()
        self._load_rxnorm_if_present()
        self._load_loinc_if_present()
        self._load_indian_brands()

        if learned_overlays:
            self._merge_learned(learned_overlays)
        self._loaded = True

        elapsed = time.time() - t0
        logger.info(
            "MedicalOntology loaded: symptoms=%d, medications=%d, investigations=%d, diagnoses=%d (%.2fs)",
            len(self.symptoms), len(self.medications),
            len(self.investigations), len(self.diagnoses), elapsed,
        )

    def fuzzy_match(self, term: str, category: str, max_edit_distance: int = 2) -> Optional[str]:
        """Fast fuzzy lookup. Returns canonical term or None."""
        term_lower = term.lower().strip()

        category_map = self._get_map(category)
        if term_lower in category_map:
            return category_map[term_lower]

        if not _HAS_SYMSPELL:
            return self._rapidfuzz_fallback(term_lower, category)

        sym = self._get_symspell(category)
        if sym is None:
            return None

        suggestions = sym.lookup(term_lower, Verbosity.CLOSEST, max_edit_distance)
        if suggestions:
            matched_key = suggestions[0].term
            return category_map.get(matched_key)
        return None

    def exact_match(self, term: str, category: str) -> Optional[str]:
        """Exact lookup only."""
        return self._get_map(category).get(term.lower().strip())

    def get_all_terms(self, category: str) -> dict[str, str]:
        """Get the full term→canonical map for a category."""
        return self._get_map(category)

    def get_vocab_set(self) -> set[str]:
        """All known terms across all categories — used for ASR word-rejoining."""
        vocab = set()
        for m in [self.symptoms, self.medications, self.investigations, self.diagnoses]:
            vocab.update(m.keys())
        return vocab

    # ── Seed vocabulary (built-in, no external files needed) ─────────────────

    def _load_seed_vocabulary(self):
        self.symptoms.update(_SEED_SYMPTOMS)
        self.medications.update(_SEED_MEDICATIONS)
        self.investigations.update(_SEED_INVESTIGATIONS)
        self.diagnoses.update(_SEED_DIAGNOSES)

    # ── Tier 1 data files (generated by scripts/fetch_ontology_data.py) ─────

    def _load_tier1_data_files(self):
        """Load ICD-10 diagnoses, OpenFDA drugs, common lab tests from TSV files."""
        # Load all TSV files from data/ontology/ using naming conventions
        # 2-col TSV: key\tcanonical (medications, brands, labs)
        # 3-col TSV with code: key\tdescription\tcode (ICD-10)
        # 3-col TSV with category: key\tcanonical\tcategory (abbreviations, hinglish, synonyms)

        for f in sorted(_DATA_DIR.glob("*.tsv")):
            count = 0
            try:
                with open(f, "r", encoding="utf-8") as fh:
                    for line in fh:
                        parts = line.strip().split("\t")
                        if len(parts) < 2:
                            continue
                        key = parts[0].strip().lower()
                        canonical = parts[1].strip()
                        if not key or not canonical:
                            continue

                        # 3-col with category (symptom/medication/diagnosis/investigation)
                        if len(parts) >= 3:
                            cat = parts[2].strip().lower()
                            if cat in ("symptom", "symptoms"):
                                self.symptoms[key] = canonical
                            elif cat in ("medication", "medications"):
                                self.medications[key] = canonical
                            elif cat in ("investigation", "investigations"):
                                self.investigations[key] = canonical
                            elif cat in ("diagnosis", "diagnoses"):
                                self.diagnoses[key] = canonical
                            else:
                                # ICD-10 style: key\tdesc\tcode → diagnosis
                                if f.name.startswith("icd10") or f.name.startswith("who_icd10"):
                                    self.diagnoses[key] = canonical
                                else:
                                    self.diagnoses[key] = canonical
                        else:
                            # 2-col: infer category from filename
                            name = f.name.lower()
                            if "drug" in name or "brand" in name or "medication" in name:
                                self.medications[key] = canonical
                            elif "lab" in name or "test" in name or "investigation" in name or "loinc" in name:
                                self.investigations[key] = canonical
                            elif "diagnos" in name or "icd" in name or "snomed_diagnos" in name:
                                self.diagnoses[key] = canonical
                            elif "symptom" in name or "snomed_symptom" in name:
                                self.symptoms[key] = canonical
                            elif "procedure" in name or "snomed_procedure" in name:
                                self.investigations[key] = canonical
                            else:
                                self.medications[key] = canonical
                        count += 1
            except Exception as e:
                logger.warning("Error loading %s: %s", f.name, e)
            if count:
                logger.info("%s: loaded %d terms", f.name, count)

    # ── SNOMED-CT loader ─────────────────────────────────────────────────────

    def _load_snomed_if_present(self):
        """Load SNOMED-CT concepts from RF2 format if available.
        Expected file: data/ontology/sct2_Description_Full-en_*.txt
        """
        snomed_files = list(_DATA_DIR.glob("sct2_Description_Full-en*.txt"))
        if not snomed_files:
            snomed_files = list(_DATA_DIR.glob("snomed_*.tsv"))
        if not snomed_files:
            return

        count = 0
        for f in snomed_files:
            try:
                with open(f, "r", encoding="utf-8") as fh:
                    reader = csv.reader(fh, delimiter="\t")
                    header = next(reader, None)
                    if not header:
                        continue
                    term_idx = _find_col(header, ["term", "description", "name"])
                    type_idx = _find_col(header, ["typeId", "semantic_tag", "type"])
                    for row in reader:
                        if len(row) <= max(term_idx, type_idx or 0):
                            continue
                        term = row[term_idx].strip()
                        sem_type = row[type_idx].strip() if type_idx is not None else ""
                        canonical = term.title()
                        key = term.lower()
                        if _is_clinical_finding(sem_type):
                            self.symptoms[key] = canonical
                            count += 1
                        elif _is_procedure_or_test(sem_type):
                            self.investigations[key] = canonical
                            count += 1
                        elif _is_disorder(sem_type):
                            self.diagnoses[key] = canonical
                            count += 1
            except Exception as e:
                logger.warning("Error loading SNOMED file %s: %s", f, e)

        logger.info("SNOMED-CT: loaded %d terms from %d files", count, len(snomed_files))

    # ── RxNorm loader ────────────────────────────────────────────────────────

    def _load_rxnorm_if_present(self):
        """Load drug names from RxNorm RXNCONSO.RRF or a simplified TSV."""
        rxnorm_files = list(_DATA_DIR.glob("RXNCONSO*")) + list(_DATA_DIR.glob("rxnorm_*.tsv"))
        if not rxnorm_files:
            return

        count = 0
        for f in rxnorm_files:
            try:
                delimiter = "|" if f.suffix == ".RRF" else "\t"
                with open(f, "r", encoding="utf-8") as fh:
                    for line in fh:
                        parts = line.strip().split(delimiter)
                        if f.suffix == ".RRF" and len(parts) > 14:
                            name = parts[14].strip()
                        elif len(parts) >= 2:
                            name = parts[1].strip() if parts[1] else parts[0].strip()
                        else:
                            continue
                        if name and len(name) > 2:
                            key = name.lower()
                            self.medications[key] = name
                            count += 1
            except Exception as e:
                logger.warning("Error loading RxNorm file %s: %s", f, e)

        logger.info("RxNorm: loaded %d drug names", count)

    # ── LOINC loader ─────────────────────────────────────────────────────────

    def _load_loinc_if_present(self):
        """Load lab test names from LOINC CSV."""
        loinc_files = list(_DATA_DIR.glob("Loinc*.csv")) + list(_DATA_DIR.glob("loinc_*.tsv"))
        if not loinc_files:
            return

        count = 0
        for f in loinc_files:
            try:
                delimiter = "," if f.suffix == ".csv" else "\t"
                with open(f, "r", encoding="utf-8") as fh:
                    reader = csv.reader(fh, delimiter=delimiter)
                    header = next(reader, None)
                    if not header:
                        continue
                    name_idx = _find_col(header, ["LONG_COMMON_NAME", "COMPONENT", "name", "test_name"])
                    short_idx = _find_col(header, ["SHORTNAME", "short_name"])
                    for row in reader:
                        if name_idx is not None and len(row) > name_idx:
                            name = row[name_idx].strip()
                            if name and len(name) > 2:
                                self.investigations[name.lower()] = name
                                count += 1
                        if short_idx is not None and len(row) > short_idx:
                            short = row[short_idx].strip()
                            if short and len(short) > 2:
                                self.investigations[short.lower()] = short
                                count += 1
            except Exception as e:
                logger.warning("Error loading LOINC file %s: %s", f, e)

        logger.info("LOINC: loaded %d investigation terms", count)

    # ── Indian brand names ───────────────────────────────────────────────────

    def _load_indian_brands(self):
        brand_file = _DATA_DIR / "indian_brands.tsv"
        if not brand_file.exists():
            self.medications.update(_SEED_INDIAN_BRANDS)
            return

        count = 0
        try:
            with open(brand_file, "r", encoding="utf-8") as fh:
                for line in fh:
                    parts = line.strip().split("\t")
                    if len(parts) >= 2:
                        brand = parts[0].strip()
                        generic = parts[1].strip()
                        self.medications[brand.lower()] = generic
                        count += 1
        except Exception as e:
            logger.warning("Error loading Indian brands: %s", e)

        self.medications.update(_SEED_INDIAN_BRANDS)
        logger.info("Indian brands: loaded %d entries", count + len(_SEED_INDIAN_BRANDS))

    # ── Hinglish transliteration variants ────────────────────────────────────

    def _load_hinglish_variants(self):
        """Auto-generate Hinglish romanization variants for common terms."""
        hinglish_file = _DATA_DIR / "hinglish_medical.tsv"
        if hinglish_file.exists():
            try:
                with open(hinglish_file, "r", encoding="utf-8") as fh:
                    for line in fh:
                        parts = line.strip().split("\t")
                        if len(parts) >= 3:
                            hinglish = parts[0].strip().lower()
                            english = parts[1].strip()
                            category = parts[2].strip()
                            if category == "symptom":
                                self.symptoms[hinglish] = english
                            elif category == "medication":
                                self.medications[hinglish] = english
                            elif category == "diagnosis":
                                self.diagnoses[hinglish] = english
            except Exception as e:
                logger.warning("Error loading Hinglish file: %s", e)

        self.symptoms.update(_SEED_HINGLISH_SYMPTOMS)
        self.medications.update(_SEED_HINGLISH_MEDICATIONS)
        self.diagnoses.update(_SEED_HINGLISH_DIAGNOSES)

    # ── Learned overlay merge ────────────────────────────────────────────────

    def _merge_learned(self, overlays: dict):
        for term, canonical in overlays.get("lexicon_term", {}).items():
            self.symptoms[term.lower()] = canonical
        for term, canonical in overlays.get("medication", {}).items():
            self.medications[term.lower()] = canonical
        for term, canonical in overlays.get("investigation", {}).items():
            self.investigations[term.lower()] = canonical
        for term, canonical in overlays.get("diagnosis", {}).items():
            self.diagnoses[term.lower()] = canonical

    # ── SymSpell index builder ───────────────────────────────────────────────

    def _build_symspell_indices(self):
        if not _HAS_SYMSPELL:
            return

        for category, attr in [
            ("symptoms", "_sym_symptoms"),
            ("medications", "_sym_medications"),
            ("investigations", "_sym_investigations"),
            ("diagnoses", "_sym_diagnoses"),
        ]:
            sym = SymSpell(max_dictionary_edit_distance=2, prefix_length=7)
            terms = self._get_map(category)
            for key in terms:
                sym.create_dictionary_entry(key, 1)
            setattr(self, attr, sym)

        logger.info("SymSpell indices built for all categories")

    # ── Helpers ──────────────────────────────────────────────────────────────

    def _get_map(self, category: str) -> dict[str, str]:
        return {
            "symptoms": self.symptoms,
            "symptom": self.symptoms,
            "medications": self.medications,
            "medication": self.medications,
            "investigations": self.investigations,
            "investigation": self.investigations,
            "diagnoses": self.diagnoses,
            "diagnosis": self.diagnoses,
        }.get(category, {})

    def _get_symspell(self, category: str) -> Optional[SymSpell]:
        return {
            "symptoms": self._sym_symptoms,
            "symptom": self._sym_symptoms,
            "medications": self._sym_medications,
            "medication": self._sym_medications,
            "investigations": self._sym_investigations,
            "investigation": self._sym_investigations,
            "diagnoses": self._sym_diagnoses,
            "diagnosis": self._sym_diagnoses,
        }.get(category)

    def _rapidfuzz_fallback(self, term: str, category: str) -> Optional[str]:
        try:
            from rapidfuzz import fuzz, process
        except ImportError:
            return None

        terms = self._get_map(category)
        if not terms:
            return None

        keys = list(terms.keys())
        match = process.extractOne(term, keys, scorer=fuzz.ratio, score_cutoff=85)
        if match:
            return terms[match[0]]
        return None


# ── Helper functions ─────────────────────────────────────────────────────────

def _find_col(header: list[str], candidates: list[str]) -> Optional[int]:
    for i, col in enumerate(header):
        if col.strip().lower() in [c.lower() for c in candidates]:
            return i
    return None if not candidates else 0


def _is_clinical_finding(sem_type: str) -> bool:
    return any(t in sem_type.lower() for t in ["finding", "symptom", "sign", "observable"])


def _is_procedure_or_test(sem_type: str) -> bool:
    return any(t in sem_type.lower() for t in ["procedure", "test", "investigation", "measurement"])


def _is_disorder(sem_type: str) -> bool:
    return any(t in sem_type.lower() for t in ["disorder", "disease", "morphologic"])


# ═════════════════════════════════════════════════════════════════════════════
# SEED VOCABULARIES — comprehensive built-in terms across all specialties
# These replace the old hand-curated maps and cover general + specialty medicine
# ═════════════════════════════════════════════════════════════════════════════

_SEED_SYMPTOMS: dict[str, str] = {
    # ── General / Constitutional ─────────────────────────────────────────
    "fever": "fever", "high fever": "fever", "high grade fever": "fever",
    "low grade fever": "low grade fever", "intermittent fever": "intermittent fever",
    "continuous fever": "fever", "persistent fever": "fever",
    "chills": "chills", "rigors": "chills", "night sweats": "night sweats",
    "sweating": "sweating", "excessive sweating": "sweating",
    "fatigue": "fatigue", "tiredness": "fatigue", "lethargy": "fatigue",
    "weakness": "weakness", "malaise": "malaise",
    "weight loss": "weight loss", "weight gain": "weight gain",
    "loss of appetite": "loss of appetite", "poor appetite": "loss of appetite",
    "anorexia": "loss of appetite",

    # ── Head / Neuro ─────────────────────────────────────────────────────
    "headache": "headache", "migraine": "migraine",
    "tension headache": "tension headache", "cluster headache": "cluster headache",
    "dizziness": "dizziness", "vertigo": "dizziness", "lightheadedness": "dizziness",
    "syncope": "syncope", "fainting": "syncope",
    "seizure": "seizure", "convulsion": "seizure", "fits": "seizure",
    "tremor": "tremor", "tremors": "tremor", "shaking": "tremor",
    "numbness": "numbness", "tingling": "tingling", "paresthesia": "tingling",
    "memory loss": "memory loss", "confusion": "confusion",
    "altered sensorium": "altered sensorium",
    "slurred speech": "slurred speech", "aphasia": "aphasia",
    "tinnitus": "tinnitus", "ringing in ears": "tinnitus",

    # ── Respiratory ──────────────────────────────────────────────────────
    "cough": "cough", "dry cough": "dry cough",
    "wet cough": "productive cough", "productive cough": "productive cough",
    "hemoptysis": "hemoptysis", "coughing blood": "hemoptysis",
    "breathlessness": "breathlessness", "shortness of breath": "breathlessness",
    "difficulty breathing": "breathlessness", "dyspnea": "breathlessness",
    "sob": "breathlessness", "orthopnea": "orthopnea",
    "wheezing": "wheezing", "stridor": "stridor",
    "chest pain": "chest pain", "chest tightness": "chest tightness",
    "pleuritic pain": "pleuritic chest pain",
    "sore throat": "sore throat", "throat pain": "sore throat",
    "throat irritation": "sore throat",
    "hoarseness": "hoarseness", "voice change": "hoarseness",
    "snoring": "snoring", "sleep apnea": "sleep apnea",
    "nasal congestion": "nasal congestion", "blocked nose": "nasal congestion",
    "stuffy nose": "nasal congestion",
    "runny nose": "runny nose", "nasal discharge": "runny nose",
    "sneezing": "sneezing", "postnasal drip": "postnasal drip",

    # ── Cardiac ──────────────────────────────────────────────────────────
    "palpitations": "palpitations", "heart racing": "palpitations",
    "rapid heartbeat": "palpitations", "tachycardia": "tachycardia",
    "bradycardia": "bradycardia", "slow heart rate": "bradycardia",
    "chest pressure": "chest pressure", "anginal pain": "anginal pain",
    "irregular heartbeat": "irregular heartbeat",
    "pedal edema": "pedal edema", "ankle swelling": "ankle swelling",
    "leg swelling": "leg swelling",
    "claudication": "claudication",

    # ── GI ───────────────────────────────────────────────────────────────
    "nausea": "nausea", "nauseous": "nausea",
    "vomiting": "vomiting", "emesis": "vomiting",
    "hematemesis": "hematemesis", "vomiting blood": "hematemesis",
    "diarrhea": "diarrhea", "loose motions": "diarrhea",
    "loose stools": "diarrhea", "watery stools": "diarrhea",
    "constipation": "constipation",
    "abdominal pain": "abdominal pain", "stomach ache": "abdominal pain",
    "stomach pain": "abdominal pain", "belly pain": "abdominal pain",
    "epigastric pain": "epigastric pain",
    "lower abdominal pain": "lower abdominal pain",
    "upper abdominal pain": "upper abdominal pain",
    "right upper quadrant pain": "RUQ pain",
    "left upper quadrant pain": "LUQ pain",
    "right lower quadrant pain": "RLQ pain",
    "left lower quadrant pain": "LLQ pain",
    "bloating": "bloating", "abdominal distension": "abdominal distension",
    "flatulence": "flatulence", "gas": "flatulence",
    "acidity": "acidity", "heartburn": "heartburn",
    "acid reflux": "acid reflux", "regurgitation": "regurgitation",
    "indigestion": "indigestion", "dyspepsia": "dyspepsia",
    "dysphagia": "dysphagia", "difficulty swallowing": "dysphagia",
    "odynophagia": "odynophagia",
    "melena": "melena", "black stools": "melena",
    "blood in stool": "rectal bleeding", "rectal bleeding": "rectal bleeding",
    "hematochezia": "hematochezia",
    "tenesmus": "tenesmus",
    "jaundice": "jaundice", "yellow eyes": "jaundice", "icterus": "jaundice",

    # ── Urinary / Renal ──────────────────────────────────────────────────
    "burning micturition": "burning micturition", "dysuria": "dysuria",
    "painful urination": "dysuria", "burning urination": "dysuria",
    "frequency of urination": "urinary frequency",
    "urinary frequency": "urinary frequency",
    "urgency": "urinary urgency", "urinary urgency": "urinary urgency",
    "nocturia": "nocturia",
    "hematuria": "hematuria", "blood in urine": "hematuria",
    "oliguria": "oliguria", "anuria": "anuria",
    "polyuria": "polyuria", "excessive urination": "polyuria",
    "urinary retention": "urinary retention",
    "incontinence": "urinary incontinence",
    "flank pain": "flank pain", "loin pain": "flank pain",
    "dark urine": "dark urine", "frothy urine": "frothy urine",
    "foamy urine": "frothy urine",

    # ── Musculoskeletal ──────────────────────────────────────────────────
    "back pain": "back pain", "lower back pain": "lower back pain",
    "backache": "back pain", "lumbago": "lower back pain",
    "neck pain": "neck pain", "cervicalgia": "neck pain",
    "shoulder pain": "shoulder pain", "frozen shoulder": "frozen shoulder",
    "knee pain": "knee pain", "hip pain": "hip pain",
    "joint pain": "joint pain", "arthralgia": "arthralgia",
    "joint stiffness": "joint stiffness", "morning stiffness": "morning stiffness",
    "joint swelling": "joint swelling",
    "muscle pain": "myalgia", "myalgia": "myalgia", "body ache": "body ache",
    "muscle cramps": "muscle cramps", "muscle spasm": "muscle spasm",
    "difficulty walking": "difficulty walking", "gait disturbance": "gait disturbance",
    "sciatica": "sciatica", "radiculopathy": "radiculopathy",

    # ── Dermatological ───────────────────────────────────────────────────
    "rash": "rash", "skin rash": "rash", "maculopapular rash": "maculopapular rash",
    "itching": "itching", "pruritus": "pruritus",
    "hives": "urticaria", "urticaria": "urticaria",
    "swelling": "swelling", "edema": "edema", "angioedema": "angioedema",
    "skin lesion": "skin lesion", "papule": "papule", "vesicle": "vesicle",
    "blister": "blister", "pustule": "pustule", "nodule": "nodule",
    "ulcer": "skin ulcer", "skin ulcer": "skin ulcer",
    "discoloration": "skin discoloration", "hyperpigmentation": "hyperpigmentation",
    "depigmentation": "depigmentation",
    "hair loss": "hair loss", "alopecia": "alopecia",
    "nail changes": "nail changes", "brittle nails": "brittle nails",
    "dry skin": "dry skin", "xeroderma": "xeroderma",
    "excessive hair growth": "hirsutism", "hirsutism": "hirsutism",
    "acne": "acne", "pimples": "acne",
    "dandruff": "dandruff", "scalp itching": "scalp itching",
    "wound": "wound", "abscess": "abscess", "boil": "boil",
    "cellulitis": "cellulitis",

    # ── Eye / ENT ────────────────────────────────────────────────────────
    "eye pain": "eye pain", "eye irritation": "eye irritation",
    "red eyes": "red eyes", "conjunctival injection": "red eyes",
    "watery eyes": "watery eyes", "epiphora": "epiphora",
    "blurred vision": "blurred vision", "vision loss": "vision loss",
    "double vision": "diplopia", "diplopia": "diplopia",
    "photophobia": "photophobia", "light sensitivity": "photophobia",
    "floaters": "floaters", "flashes": "flashes",
    "eye discharge": "eye discharge",
    "ear pain": "ear pain", "earache": "ear pain", "otalgia": "otalgia",
    "hearing loss": "hearing loss", "deafness": "hearing loss",
    "ear discharge": "ear discharge", "otorrhea": "otorrhea",
    "nosebleed": "epistaxis", "epistaxis": "epistaxis",
    "toothache": "toothache", "dental pain": "toothache",
    "mouth ulcer": "mouth ulcer", "oral ulcer": "mouth ulcer",
    "difficulty opening mouth": "trismus",
    "dry mouth": "xerostomia",
    "bad breath": "halitosis",

    # ── Endocrine ────────────────────────────────────────────────────────
    "excessive thirst": "polydipsia", "polydipsia": "polydipsia",
    "excessive hunger": "polyphagia", "polyphagia": "polyphagia",
    "cold intolerance": "cold intolerance",
    "heat intolerance": "heat intolerance",
    "goiter": "goiter", "neck swelling": "neck swelling",
    "galactorrhea": "galactorrhea",

    # ── Gynecological ────────────────────────────────────────────────────
    "irregular periods": "irregular menstruation",
    "heavy periods": "menorrhagia", "menorrhagia": "menorrhagia",
    "absent periods": "amenorrhea", "amenorrhea": "amenorrhea",
    "painful periods": "dysmenorrhea", "dysmenorrhea": "dysmenorrhea",
    "vaginal discharge": "vaginal discharge", "leucorrhea": "leucorrhea",
    "vaginal bleeding": "vaginal bleeding",
    "pelvic pain": "pelvic pain",
    "breast lump": "breast lump", "breast pain": "mastalgia",
    "hot flashes": "hot flashes", "menopausal symptoms": "menopausal symptoms",

    # ── Psychiatric ──────────────────────────────────────────────────────
    "anxiety": "anxiety", "panic attack": "panic attack",
    "depression": "depressed mood", "sadness": "depressed mood",
    "insomnia": "insomnia", "sleep problems": "insomnia",
    "difficulty sleeping": "insomnia",
    "excessive sleep": "hypersomnia",
    "restlessness": "restlessness", "agitation": "agitation",
    "hallucination": "hallucination",
    "suicidal thoughts": "suicidal ideation",
    "mood swings": "mood swings",
    "poor concentration": "poor concentration",
    "irritability": "irritability",

    # ── Pediatric (common) ───────────────────────────────────────────────
    "failure to thrive": "failure to thrive",
    "poor feeding": "poor feeding",
    "excessive crying": "excessive crying",
    "delayed milestones": "delayed milestones",

    # ── ASR misspellings of common English terms ─────────────────────────
    "fevre": "fever", "fver": "fever", "fevr": "fever",
    "headach": "headache", "hedache": "headache",
    "vomitin": "vomiting", "vomitting": "vomiting",
    "diarrhoea": "diarrhea", "diarreia": "diarrhea", "diarea": "diarrhea",
    "sweling": "swelling", "swollne": "swelling",
    "cold": "cold", "common cold": "cold",
    "pallor": "pallor", "pale": "pallor",
    "bleeding": "bleeding",
    "cavity": "cavity",
}

_SEED_MEDICATIONS: dict[str, str] = {
    # ── Antipyretics / Analgesics ────────────────────────────────────────
    "paracetamol": "paracetamol", "acetaminophen": "paracetamol",
    "ibuprofen": "ibuprofen", "diclofenac": "diclofenac",
    "naproxen": "naproxen", "aspirin": "aspirin",
    "aceclofenac": "aceclofenac", "mefenamic acid": "mefenamic acid",
    "piroxicam": "piroxicam", "indomethacin": "indomethacin",
    "tramadol": "tramadol", "ketorolac": "ketorolac",
    "nimesulide": "nimesulide", "etoricoxib": "etoricoxib",
    "celecoxib": "celecoxib",

    # ── Antibiotics ──────────────────────────────────────────────────────
    "amoxicillin": "amoxicillin", "amoxyclav": "amoxicillin-clavulanate",
    "amoxicillin clavulanate": "amoxicillin-clavulanate",
    "augmentin": "amoxicillin-clavulanate",
    "azithromycin": "azithromycin", "cefixime": "cefixime",
    "ceftriaxone": "ceftriaxone", "cephalexin": "cephalexin",
    "ciprofloxacin": "ciprofloxacin", "ofloxacin": "ofloxacin",
    "norfloxacin": "norfloxacin", "levofloxacin": "levofloxacin",
    "moxifloxacin": "moxifloxacin",
    "metronidazole": "metronidazole", "ornidazole": "ornidazole",
    "doxycycline": "doxycycline", "tetracycline": "tetracycline",
    "erythromycin": "erythromycin", "clarithromycin": "clarithromycin",
    "clindamycin": "clindamycin",
    "cotrimoxazole": "cotrimoxazole",
    "nitrofurantoin": "nitrofurantoin",
    "linezolid": "linezolid", "vancomycin": "vancomycin",
    "meropenem": "meropenem", "piperacillin": "piperacillin-tazobactam",
    "cefuroxime": "cefuroxime", "cefpodoxime": "cefpodoxime",
    "ceftazidime": "ceftazidime", "cefoperazone": "cefoperazone",
    "gentamicin": "gentamicin", "amikacin": "amikacin",
    "fluconazole": "fluconazole", "itraconazole": "itraconazole",
    "clotrimazole": "clotrimazole", "terbinafine": "terbinafine",
    "acyclovir": "acyclovir", "valacyclovir": "valacyclovir",

    # ── GI medications ───────────────────────────────────────────────────
    "omeprazole": "omeprazole", "pantoprazole": "pantoprazole",
    "rabeprazole": "rabeprazole", "esomeprazole": "esomeprazole",
    "lansoprazole": "lansoprazole",
    "ranitidine": "ranitidine", "famotidine": "famotidine",
    "domperidone": "domperidone", "metoclopramide": "metoclopramide",
    "ondansetron": "ondansetron",
    "sucralfate": "sucralfate", "antacid": "antacid",
    "loperamide": "loperamide",
    "lactulose": "lactulose", "bisacodyl": "bisacodyl",
    "polyethylene glycol": "polyethylene glycol",
    "ursodeoxycholic acid": "ursodeoxycholic acid",

    # ── Antihistamines / Allergy ─────────────────────────────────────────
    "cetirizine": "cetirizine", "levocetirizine": "levocetirizine",
    "fexofenadine": "fexofenadine", "loratadine": "loratadine",
    "desloratadine": "desloratadine",
    "chlorpheniramine": "chlorpheniramine",
    "hydroxyzine": "hydroxyzine",
    "montelukast": "montelukast",

    # ── Cardiac / Antihypertensives ──────────────────────────────────────
    "amlodipine": "amlodipine", "nifedipine": "nifedipine",
    "atenolol": "atenolol", "metoprolol": "metoprolol",
    "propranolol": "propranolol", "carvedilol": "carvedilol",
    "nebivolol": "nebivolol", "bisoprolol": "bisoprolol",
    "enalapril": "enalapril", "ramipril": "ramipril",
    "lisinopril": "lisinopril", "perindopril": "perindopril",
    "losartan": "losartan", "telmisartan": "telmisartan",
    "valsartan": "valsartan", "olmesartan": "olmesartan",
    "irbesartan": "irbesartan",
    "hydrochlorothiazide": "hydrochlorothiazide",
    "furosemide": "furosemide", "spironolactone": "spironolactone",
    "torsemide": "torsemide", "chlorthalidone": "chlorthalidone",
    "diltiazem": "diltiazem", "verapamil": "verapamil",
    "clopidogrel": "clopidogrel", "ticagrelor": "ticagrelor",
    "warfarin": "warfarin", "heparin": "heparin",
    "enoxaparin": "enoxaparin", "rivaroxaban": "rivaroxaban",
    "apixaban": "apixaban", "dabigatran": "dabigatran",
    "atorvastatin": "atorvastatin", "rosuvastatin": "rosuvastatin",
    "simvastatin": "simvastatin", "fenofibrate": "fenofibrate",
    "nitroglycerin": "nitroglycerin", "isosorbide": "isosorbide dinitrate",
    "digoxin": "digoxin", "amiodarone": "amiodarone",

    # ── Diabetes ─────────────────────────────────────────────────────────
    "metformin": "metformin", "glimepiride": "glimepiride",
    "gliclazide": "gliclazide", "glipizide": "glipizide",
    "sitagliptin": "sitagliptin", "vildagliptin": "vildagliptin",
    "teneligliptin": "teneligliptin", "linagliptin": "linagliptin",
    "empagliflozin": "empagliflozin", "dapagliflozin": "dapagliflozin",
    "canagliflozin": "canagliflozin",
    "pioglitazone": "pioglitazone",
    "insulin": "insulin", "insulin glargine": "insulin glargine",
    "insulin aspart": "insulin aspart", "insulin lispro": "insulin lispro",
    "human mixtard": "human mixtard",
    "voglibose": "voglibose", "acarbose": "acarbose",

    # ── Respiratory ──────────────────────────────────────────────────────
    "salbutamol": "salbutamol", "albuterol": "salbutamol",
    "ipratropium": "ipratropium", "tiotropium": "tiotropium",
    "formoterol": "formoterol", "salmeterol": "salmeterol",
    "budesonide": "budesonide", "fluticasone": "fluticasone",
    "beclomethasone": "beclomethasone",
    "montelukast": "montelukast", "theophylline": "theophylline",
    "dextromethorphan": "dextromethorphan",
    "guaifenesin": "guaifenesin", "ambroxol": "ambroxol",
    "bromhexine": "bromhexine", "acetylcysteine": "acetylcysteine",

    # ── Steroids ─────────────────────────────────────────────────────────
    "prednisolone": "prednisolone", "prednisone": "prednisone",
    "dexamethasone": "dexamethasone", "methylprednisolone": "methylprednisolone",
    "hydrocortisone": "hydrocortisone",
    "betamethasone": "betamethasone", "triamcinolone": "triamcinolone",

    # ── Neuro / Psych ────────────────────────────────────────────────────
    "gabapentin": "gabapentin", "pregabalin": "pregabalin",
    "carbamazepine": "carbamazepine", "phenytoin": "phenytoin",
    "valproate": "valproate", "levetiracetam": "levetiracetam",
    "topiramate": "topiramate", "lamotrigine": "lamotrigine",
    "amitriptyline": "amitriptyline", "nortriptyline": "nortriptyline",
    "fluoxetine": "fluoxetine", "sertraline": "sertraline",
    "escitalopram": "escitalopram", "paroxetine": "paroxetine",
    "duloxetine": "duloxetine", "venlafaxine": "venlafaxine",
    "mirtazapine": "mirtazapine",
    "alprazolam": "alprazolam", "clonazepam": "clonazepam",
    "lorazepam": "lorazepam", "diazepam": "diazepam",
    "zolpidem": "zolpidem",
    "risperidone": "risperidone", "olanzapine": "olanzapine",
    "quetiapine": "quetiapine", "haloperidol": "haloperidol",
    "lithium": "lithium",
    "donepezil": "donepezil", "memantine": "memantine",
    "levodopa": "levodopa", "carbidopa": "carbidopa",
    "ropinirole": "ropinirole", "pramipexole": "pramipexole",
    "sumatriptan": "sumatriptan", "rizatriptan": "rizatriptan",

    # ── Supplements / Vitamins ───────────────────────────────────────────
    "methylcobalamin": "methylcobalamin", "vitamin b12": "vitamin B12",
    "folic acid": "folic acid", "iron": "iron supplement",
    "ferrous sulfate": "ferrous sulfate", "ferrous fumarate": "ferrous fumarate",
    "calcium": "calcium supplement", "calcium carbonate": "calcium carbonate",
    "vitamin d": "vitamin D", "cholecalciferol": "cholecalciferol",
    "vitamin d3": "cholecalciferol",
    "vitamin c": "vitamin C", "ascorbic acid": "vitamin C",
    "zinc": "zinc supplement", "multivitamin": "multivitamin",
    "omega 3": "omega-3 fatty acids",
    "probiotics": "probiotics", "saccharomyces": "saccharomyces boulardii",

    # ── Ophthalmology ────────────────────────────────────────────────────
    "timolol": "timolol", "latanoprost": "latanoprost",
    "brimonidine": "brimonidine", "dorzolamide": "dorzolamide",
    "pilocarpine": "pilocarpine",
    "tobramycin": "tobramycin eye drops",
    "moxifloxacin eye drops": "moxifloxacin eye drops",
    "artificial tears": "artificial tears",
    "cyclopentolate": "cyclopentolate",

    # ── Dermatology ──────────────────────────────────────────────────────
    "clobetasol": "clobetasol", "mometasone": "mometasone",
    "fusidic acid": "fusidic acid", "mupirocin": "mupirocin",
    "permethrin": "permethrin", "ivermectin": "ivermectin",
    "isotretinoin": "isotretinoin", "adapalene": "adapalene",
    "benzoyl peroxide": "benzoyl peroxide",
    "ketoconazole cream": "ketoconazole cream",
    "calamine": "calamine lotion",

    # ── Oncology (common) ────────────────────────────────────────────────
    "tamoxifen": "tamoxifen", "letrozole": "letrozole",
    "cyclophosphamide": "cyclophosphamide", "methotrexate": "methotrexate",
    "5 fluorouracil": "5-fluorouracil", "capecitabine": "capecitabine",
    "cisplatin": "cisplatin", "carboplatin": "carboplatin",
    "paclitaxel": "paclitaxel", "docetaxel": "docetaxel",
    "imatinib": "imatinib", "rituximab": "rituximab",
    "trastuzumab": "trastuzumab",

    # ── Rheumatology ─────────────────────────────────────────────────────
    "hydroxychloroquine": "hydroxychloroquine",
    "sulfasalazine": "sulfasalazine",
    "leflunomide": "leflunomide",
    "colchicine": "colchicine", "allopurinol": "allopurinol",
    "febuxostat": "febuxostat",

    # ── Thyroid ──────────────────────────────────────────────────────────
    "levothyroxine": "levothyroxine", "thyroxine": "levothyroxine",
    "carbimazole": "carbimazole", "methimazole": "methimazole",
    "propylthiouracil": "propylthiouracil",

    # ── Others ───────────────────────────────────────────────────────────
    "sildenafil": "sildenafil", "tadalafil": "tadalafil",
    "tamsulosin": "tamsulosin", "finasteride": "finasteride",
    "dutasteride": "dutasteride",
    "misoprostol": "misoprostol",
    "tranexamic acid": "tranexamic acid",
    "ethamsylate": "ethamsylate",
}

_SEED_INVESTIGATIONS: dict[str, str] = {
    # ── Hematology ───────────────────────────────────────────────────────
    "cbc": "CBC", "complete blood count": "CBC", "hemogram": "CBC",
    "esr": "ESR", "crp": "CRP", "c reactive protein": "CRP",
    "procalcitonin": "Procalcitonin",
    "peripheral smear": "Peripheral Smear",
    "reticulocyte count": "Reticulocyte Count",
    "coagulation profile": "Coagulation Profile",
    "pt inr": "PT/INR", "aptt": "aPTT",
    "d dimer": "D-Dimer", "fibrinogen": "Fibrinogen",
    "blood group": "Blood Group", "cross match": "Cross Match",

    # ── Biochemistry ─────────────────────────────────────────────────────
    "blood sugar": "Blood Glucose", "blood glucose": "Blood Glucose",
    "fasting sugar": "Fasting Blood Glucose", "fbs": "Fasting Blood Sugar",
    "pp sugar": "Post-Prandial Glucose", "rbs": "Random Blood Sugar",
    "hba1c": "HbA1c", "glycated hemoglobin": "HbA1c",
    "lft": "Liver Function Test", "liver function": "Liver Function Test",
    "liver function test": "Liver Function Test",
    "sgot": "SGOT/AST", "sgpt": "SGPT/ALT", "ast": "AST", "alt": "ALT",
    "bilirubin": "Bilirubin", "albumin": "Albumin",
    "alkaline phosphatase": "Alkaline Phosphatase", "alp": "ALP",
    "ggt": "GGT", "gamma gt": "GGT",
    "rft": "Renal Function Test", "kidney function": "Renal Function Test",
    "renal function": "Renal Function Test",
    "creatinine": "Creatinine", "blood urea": "Blood Urea",
    "bun": "BUN", "uric acid": "Uric Acid",
    "egfr": "eGFR",
    "electrolytes": "Electrolytes", "sodium": "Sodium",
    "potassium": "Potassium", "chloride": "Chloride",
    "calcium": "Serum Calcium", "magnesium": "Serum Magnesium",
    "phosphorus": "Serum Phosphorus",
    "lipid profile": "Lipid Profile", "cholesterol": "Cholesterol",
    "triglycerides": "Triglycerides", "hdl": "HDL", "ldl": "LDL",
    "vldl": "VLDL",
    "total protein": "Total Protein",
    "amylase": "Amylase", "lipase": "Lipase",
    "troponin": "Troponin", "troponin i": "Troponin I",
    "troponin t": "Troponin T",
    "bnp": "BNP", "nt pro bnp": "NT-proBNP",
    "cpk": "CPK", "ldh": "LDH",
    "iron studies": "Iron Studies", "serum iron": "Serum Iron",
    "tibc": "TIBC", "ferritin": "Ferritin",
    "vitamin d": "Vitamin D Level", "vitamin b12": "Vitamin B12 Level",
    "folate": "Folate Level",

    # ── Thyroid ──────────────────────────────────────────────────────────
    "thyroid test": "Thyroid Panel", "thyroid function": "Thyroid Panel",
    "tsh": "TSH", "t3": "T3", "t4": "T4", "ft3": "Free T3", "ft4": "Free T4",
    "anti tpo": "Anti-TPO", "thyroid antibodies": "Thyroid Antibodies",

    # ── Hormones ─────────────────────────────────────────────────────────
    "cortisol": "Cortisol", "acth": "ACTH",
    "prolactin": "Prolactin", "growth hormone": "Growth Hormone",
    "testosterone": "Testosterone", "estradiol": "Estradiol",
    "fsh": "FSH", "lh": "LH", "beta hcg": "Beta HCG",
    "insulin level": "Insulin Level",
    "pth": "PTH",

    # ── Urine ────────────────────────────────────────────────────────────
    "urine test": "Urine Test", "urine routine": "Urine Routine",
    "urine r/e": "Urine Routine", "urine re": "Urine Routine",
    "urine culture": "Urine Culture",
    "urine microalbumin": "Urine Microalbumin",
    "24 hour urine protein": "24-Hour Urine Protein",
    "urine pregnancy test": "Urine Pregnancy Test",

    # ── Microbiology ─────────────────────────────────────────────────────
    "blood culture": "Blood Culture",
    "culture sensitivity": "Culture & Sensitivity",
    "throat swab": "Throat Swab Culture",
    "sputum culture": "Sputum Culture",
    "stool test": "Stool Examination", "stool routine": "Stool Examination",
    "stool culture": "Stool Culture",
    "stool occult blood": "Stool Occult Blood",
    "wound culture": "Wound Culture",

    # ── Serology / Infectious ────────────────────────────────────────────
    "dengue test": "Dengue NS1/IgM", "dengue ns1": "Dengue NS1",
    "dengue igm": "Dengue IgM",
    "malaria test": "Malaria RDT", "malaria rdt": "Malaria RDT",
    "widal": "Widal Test", "typhidot": "Typhidot",
    "covid test": "COVID Antigen", "covid rtpcr": "COVID RT-PCR",
    "rapid antigen": "Rapid Antigen Test",
    "hiv test": "HIV Test", "hiv elisa": "HIV ELISA",
    "hbsag": "HBsAg", "hepatitis b": "HBsAg",
    "anti hcv": "Anti-HCV", "hepatitis c": "Anti-HCV",
    "vdrl": "VDRL", "rpr": "RPR",
    "aso titer": "ASO Titer", "ra factor": "RA Factor",
    "ana": "ANA", "anti ccp": "Anti-CCP",
    "mantoux test": "Mantoux Test", "ppd": "PPD Test",

    # ── Imaging ──────────────────────────────────────────────────────────
    "x-ray": "X-Ray", "x ray": "X-Ray", "xray": "X-Ray",
    "chest x-ray": "Chest X-Ray", "chest xray": "Chest X-Ray",
    "ultrasound": "Ultrasound", "usg": "USG", "sonography": "Sonography",
    "usg abdomen": "USG Abdomen", "usg pelvis": "USG Pelvis",
    "usg kub": "USG KUB",
    "ct scan": "CT Scan", "ctscan": "CT Scan",
    "hrct": "HRCT", "hrct chest": "HRCT Chest",
    "ct brain": "CT Brain", "ct abdomen": "CT Abdomen",
    "mri": "MRI", "mri brain": "MRI Brain", "mri spine": "MRI Spine",
    "mri knee": "MRI Knee",
    "pet scan": "PET Scan", "pet ct": "PET-CT",
    "mammography": "Mammography",
    "bone scan": "Bone Scan",
    "doppler": "Doppler", "venous doppler": "Venous Doppler",
    "arterial doppler": "Arterial Doppler",
    "carotid doppler": "Carotid Doppler",

    # ── Cardiac ──────────────────────────────────────────────────────────
    "ecg": "ECG", "ekg": "ECG", "electrocardiogram": "ECG",
    "echo": "Echocardiography", "echocardiogram": "Echocardiography",
    "2d echo": "2D Echo",
    "tmt": "TMT (Stress Test)", "stress test": "Stress Test",
    "holter": "Holter Monitor",
    "coronary angiography": "Coronary Angiography",

    # ── Pulmonary ────────────────────────────────────────────────────────
    "pft": "PFT", "pulmonary function": "PFT",
    "spirometry": "Spirometry",
    "abg": "ABG", "arterial blood gas": "ABG",

    # ── GI ───────────────────────────────────────────────────────────────
    "endoscopy": "Upper GI Endoscopy", "upper gi endoscopy": "Upper GI Endoscopy",
    "colonoscopy": "Colonoscopy",
    "ercp": "ERCP",
    "barium swallow": "Barium Swallow",
    "barium meal": "Barium Meal",

    # ── Neuro ────────────────────────────────────────────────────────────
    "eeg": "EEG", "electroencephalogram": "EEG",
    "emg": "EMG", "nerve conduction": "NCV",
    "ncv": "NCV",
    "lumbar puncture": "Lumbar Puncture", "csf analysis": "CSF Analysis",

    # ── Ophthalmology ────────────────────────────────────────────────────
    "fundoscopy": "Fundoscopy", "tonometry": "Tonometry",
    "slit lamp": "Slit Lamp Examination",
    "oct": "OCT", "visual field": "Visual Field Test",
    "refraction": "Refraction",

    # ── Bone / Rheumatology ──────────────────────────────────────────────
    "dexa": "DEXA Scan", "bone density": "DEXA Scan",
    "bone mineral density": "DEXA Scan",

    # ── Dental ───────────────────────────────────────────────────────────
    "opg": "OPG", "orthopantomogram": "OPG",
    "iopa": "IOPA", "rct": "Root Canal Treatment",
    "root canal": "Root Canal Treatment",
    "scaling": "Dental Scaling", "filling": "Cavity Filling",
    "extraction": "Tooth Extraction",

    # ── Biopsy ───────────────────────────────────────────────────────────
    "biopsy": "Biopsy", "fnac": "FNAC",
    "histopathology": "Histopathology",

    # ── Hinglish investigations ──────────────────────────────────────────
    "khoon ki jaanch": "Blood Test", "खून की जांच": "Blood Test",
    "blood test": "Blood Test", "blood work": "Blood Test",
}

_SEED_DIAGNOSES: dict[str, str] = {
    # ── Infections ───────────────────────────────────────────────────────
    "viral fever": "Viral Fever", "viral infection": "Viral Infection",
    "dengue": "Dengue Fever", "dengue fever": "Dengue Fever",
    "typhoid": "Typhoid Fever", "enteric fever": "Typhoid Fever",
    "malaria": "Malaria",
    "covid": "COVID-19", "covid 19": "COVID-19", "corona": "COVID-19",
    "influenza": "Influenza", "flu": "Influenza",
    "chickenpox": "Varicella", "varicella": "Varicella",
    "mumps": "Mumps", "measles": "Measles",
    "tuberculosis": "Tuberculosis", "tb": "Tuberculosis",
    "pulmonary tb": "Pulmonary Tuberculosis",
    "extrapulmonary tb": "Extrapulmonary Tuberculosis",
    "scabies": "Scabies", "fungal infection": "Fungal Infection",
    "ringworm": "Dermatophytosis", "tinea": "Dermatophytosis",
    "cellulitis": "Cellulitis",
    "hepatitis": "Hepatitis", "hepatitis a": "Hepatitis A",
    "hepatitis b": "Hepatitis B", "hepatitis c": "Hepatitis C",
    "herpes": "Herpes Simplex", "herpes zoster": "Herpes Zoster",
    "shingles": "Herpes Zoster",
    "amebiasis": "Amebiasis", "giardiasis": "Giardiasis",
    "sepsis": "Sepsis", "septicemia": "Septicemia",
    "abscess": "Abscess",

    # ── Respiratory ──────────────────────────────────────────────────────
    "urti": "URTI", "upper respiratory tract infection": "URTI",
    "lrti": "LRTI", "lower respiratory tract infection": "LRTI",
    "pneumonia": "Pneumonia", "bronchitis": "Bronchitis",
    "bronchopneumonia": "Bronchopneumonia",
    "asthma": "Asthma", "bronchial asthma": "Bronchial Asthma",
    "copd": "COPD", "emphysema": "Emphysema",
    "pleural effusion": "Pleural Effusion",
    "pneumothorax": "Pneumothorax",
    "pharyngitis": "Pharyngitis", "tonsillitis": "Tonsillitis",
    "laryngitis": "Laryngitis", "sinusitis": "Sinusitis",
    "allergic rhinitis": "Allergic Rhinitis",
    "nasal polyp": "Nasal Polyp",
    "otitis media": "Otitis Media", "otitis externa": "Otitis Externa",
    "conjunctivitis": "Conjunctivitis",

    # ── Cardiac ──────────────────────────────────────────────────────────
    "hypertension": "Hypertension", "high bp": "Hypertension",
    "high blood pressure": "Hypertension",
    "heart attack": "Myocardial Infarction",
    "myocardial infarction": "Myocardial Infarction",
    "angina": "Angina", "unstable angina": "Unstable Angina",
    "heart failure": "Heart Failure", "chf": "Congestive Heart Failure",
    "atrial fibrillation": "Atrial Fibrillation",
    "arrhythmia": "Arrhythmia",
    "valvular heart disease": "Valvular Heart Disease",
    "rheumatic heart disease": "Rheumatic Heart Disease",
    "dvt": "Deep Vein Thrombosis", "pulmonary embolism": "Pulmonary Embolism",
    "peripheral vascular disease": "Peripheral Vascular Disease",

    # ── Metabolic / Endocrine ────────────────────────────────────────────
    "diabetes": "Diabetes Mellitus", "type 2 diabetes": "Type 2 Diabetes",
    "type 1 diabetes": "Type 1 Diabetes",
    "diabetic ketoacidosis": "DKA", "dka": "DKA",
    "diabetic neuropathy": "Diabetic Neuropathy",
    "diabetic nephropathy": "Diabetic Nephropathy",
    "diabetic retinopathy": "Diabetic Retinopathy",
    "hypothyroidism": "Hypothyroidism", "hyperthyroidism": "Hyperthyroidism",
    "thyroid disorder": "Thyroid Disorder",
    "cushing syndrome": "Cushing Syndrome",
    "addison disease": "Addison Disease",
    "pheochromocytoma": "Pheochromocytoma",
    "anemia": "Anemia", "iron deficiency anemia": "Iron Deficiency Anemia",
    "b12 deficiency": "Vitamin B12 Deficiency",
    "megaloblastic anemia": "Megaloblastic Anemia",
    "thalassemia": "Thalassemia", "sickle cell": "Sickle Cell Disease",
    "gout": "Gout", "hyperuricemia": "Hyperuricemia",
    "hyperlipidemia": "Hyperlipidemia", "dyslipidemia": "Dyslipidemia",
    "obesity": "Obesity",
    "metabolic syndrome": "Metabolic Syndrome",

    # ── GI ───────────────────────────────────────────────────────────────
    "gastritis": "Gastritis", "acute gastritis": "Acute Gastritis",
    "gastroenteritis": "Acute Gastroenteritis",
    "food poisoning": "Food Poisoning",
    "gerd": "GERD", "peptic ulcer": "Peptic Ulcer Disease",
    "duodenal ulcer": "Duodenal Ulcer", "gastric ulcer": "Gastric Ulcer",
    "ibs": "Irritable Bowel Syndrome",
    "inflammatory bowel disease": "Inflammatory Bowel Disease",
    "crohns disease": "Crohn's Disease", "ulcerative colitis": "Ulcerative Colitis",
    "appendicitis": "Appendicitis",
    "cholecystitis": "Cholecystitis", "cholelithiasis": "Cholelithiasis",
    "gallstones": "Cholelithiasis",
    "pancreatitis": "Pancreatitis",
    "liver cirrhosis": "Liver Cirrhosis", "fatty liver": "Fatty Liver",
    "nafld": "NAFLD",
    "hemorrhoids": "Hemorrhoids", "piles": "Hemorrhoids",
    "anal fissure": "Anal Fissure",
    "hernia": "Hernia", "inguinal hernia": "Inguinal Hernia",
    "umbilical hernia": "Umbilical Hernia",

    # ── Renal / Urological ───────────────────────────────────────────────
    "uti": "UTI", "urinary tract infection": "UTI",
    "pyelonephritis": "Pyelonephritis",
    "kidney stones": "Nephrolithiasis", "renal calculi": "Nephrolithiasis",
    "nephrolithiasis": "Nephrolithiasis",
    "chronic kidney disease": "CKD", "ckd": "CKD",
    "acute kidney injury": "AKI", "aki": "AKI",
    "nephrotic syndrome": "Nephrotic Syndrome",
    "bph": "BPH", "benign prostatic hyperplasia": "BPH",
    "prostatitis": "Prostatitis",

    # ── Neuro ────────────────────────────────────────────────────────────
    "migraine": "Migraine", "tension headache": "Tension Headache",
    "stroke": "Stroke", "cerebrovascular accident": "CVA",
    "tia": "TIA",
    "epilepsy": "Epilepsy", "seizure disorder": "Seizure Disorder",
    "parkinsons": "Parkinson's Disease",
    "alzheimers": "Alzheimer's Disease",
    "bell palsy": "Bell's Palsy", "bells palsy": "Bell's Palsy",
    "trigeminal neuralgia": "Trigeminal Neuralgia",
    "carpal tunnel": "Carpal Tunnel Syndrome",
    "meningitis": "Meningitis", "encephalitis": "Encephalitis",
    "neuropathy": "Neuropathy", "peripheral neuropathy": "Peripheral Neuropathy",
    "vertigo": "Vertigo", "bppv": "BPPV",
    "menieres disease": "Meniere's Disease",

    # ── Musculoskeletal ──────────────────────────────────────────────────
    "osteoarthritis": "Osteoarthritis",
    "rheumatoid arthritis": "Rheumatoid Arthritis",
    "spondylitis": "Spondylitis", "ankylosing spondylitis": "Ankylosing Spondylitis",
    "disc prolapse": "Disc Prolapse", "slip disc": "Disc Prolapse",
    "frozen shoulder": "Frozen Shoulder",
    "plantar fasciitis": "Plantar Fasciitis",
    "tennis elbow": "Lateral Epicondylitis",
    "fracture": "Fracture",
    "osteoporosis": "Osteoporosis",
    "fibromyalgia": "Fibromyalgia",
    "sle": "Systemic Lupus Erythematosus",
    "lupus": "Systemic Lupus Erythematosus",

    # ── Dermatology ──────────────────────────────────────────────────────
    "eczema": "Eczema", "dermatitis": "Dermatitis",
    "contact dermatitis": "Contact Dermatitis",
    "psoriasis": "Psoriasis",
    "vitiligo": "Vitiligo",
    "acne vulgaris": "Acne Vulgaris",
    "rosacea": "Rosacea",
    "alopecia areata": "Alopecia Areata",
    "seborrheic dermatitis": "Seborrheic Dermatitis",
    "lichen planus": "Lichen Planus",
    "pemphigus": "Pemphigus",
    "urticaria": "Urticaria",
    "warts": "Verruca", "verruca": "Verruca",
    "molluscum": "Molluscum Contagiosum",

    # ── Ophthalmology ────────────────────────────────────────────────────
    "cataract": "Cataract",
    "glaucoma": "Glaucoma",
    "diabetic retinopathy": "Diabetic Retinopathy",
    "macular degeneration": "Macular Degeneration",
    "keratitis": "Keratitis",
    "blepharitis": "Blepharitis",
    "chalazion": "Chalazion", "stye": "Hordeolum",
    "refractive error": "Refractive Error",
    "myopia": "Myopia", "hyperopia": "Hyperopia",

    # ── Gynecology ───────────────────────────────────────────────────────
    "pcos": "PCOS", "polycystic ovarian syndrome": "PCOS",
    "endometriosis": "Endometriosis",
    "fibroids": "Uterine Fibroids",
    "ovarian cyst": "Ovarian Cyst",
    "cervicitis": "Cervicitis",
    "pelvic inflammatory disease": "PID", "pid": "PID",
    "vaginitis": "Vaginitis",
    "menopause": "Menopause",

    # ── Psychiatry ───────────────────────────────────────────────────────
    "anxiety disorder": "Anxiety Disorder", "gad": "GAD",
    "depression": "Major Depressive Disorder",
    "bipolar disorder": "Bipolar Disorder",
    "schizophrenia": "Schizophrenia",
    "ocd": "OCD", "obsessive compulsive disorder": "OCD",
    "ptsd": "PTSD",
    "insomnia": "Insomnia",
    "substance use disorder": "Substance Use Disorder",
    "alcohol dependence": "Alcohol Dependence",

    # ── Pediatric ────────────────────────────────────────────────────────
    "hand foot mouth disease": "HFMD",
    "croup": "Croup",
    "bronchiolitis": "Bronchiolitis",
    "febrile seizure": "Febrile Seizure",
    "kwashiorkor": "Kwashiorkor",
    "marasmus": "Marasmus",
    "rickets": "Rickets",

    # ── Dental ───────────────────────────────────────────────────────────
    "dental caries": "Dental Caries",
    "periodontitis": "Periodontitis",
    "gingivitis": "Gingivitis",
    "periapical abscess": "Periapical Abscess",
    "malocclusion": "Malocclusion",

    # ── Oncology ─────────────────────────────────────────────────────────
    "breast cancer": "Breast Cancer",
    "lung cancer": "Lung Cancer",
    "colorectal cancer": "Colorectal Cancer",
    "prostate cancer": "Prostate Cancer",
    "cervical cancer": "Cervical Cancer",
    "oral cancer": "Oral Cancer",
    "leukemia": "Leukemia", "lymphoma": "Lymphoma",
    "multiple myeloma": "Multiple Myeloma",

    # ── Hinglish diagnoses ───────────────────────────────────────────────
    "sugar ki bimari": "Diabetes Mellitus", "madhumeh": "Diabetes Mellitus",
    "bp high": "Hypertension", "bp badhna": "Hypertension",
    "lakwa": "Paralysis",
    "motiyabind": "Cataract",
    "safed daag": "Vitiligo",
    "शुगर": "Diabetes Mellitus", "मधुमेह": "Diabetes Mellitus",
    "मोतियाबिंद": "Cataract",
    "खून की कमी": "Anemia", "khoon ki kami": "Anemia",
}

# ── Indian brand name → generic mapping ──────────────────────────────────────

_SEED_INDIAN_BRANDS: dict[str, str] = {
    "dolo": "paracetamol", "dolo 650": "paracetamol 650mg",
    "crocin": "paracetamol", "crocin advance": "paracetamol",
    "calpol": "paracetamol",
    "combiflam": "ibuprofen + paracetamol",
    "saridon": "propyphenazone + paracetamol + caffeine",
    "sumo": "nimesulide + paracetamol",
    "voveran": "diclofenac", "voveran sr": "diclofenac SR",
    "zerodol": "aceclofenac", "zerodol sp": "aceclofenac + serratiopeptidase",
    "zerodol p": "aceclofenac + paracetamol",
    "hifenac": "aceclofenac",
    "mox": "amoxicillin", "mox cv": "amoxicillin-clavulanate",
    "novamox": "amoxicillin",
    "augmentin": "amoxicillin-clavulanate",
    "azee": "azithromycin", "azithral": "azithromycin",
    "zithromax": "azithromycin",
    "taxim o": "cefixime", "ceftas": "cefixime",
    "monocef": "ceftriaxone",
    "ciplox": "ciprofloxacin", "cifran": "ciprofloxacin",
    "levoflox": "levofloxacin",
    "flagyl": "metronidazole", "metrogyl": "metronidazole",
    "ornof": "ofloxacin + ornidazole",
    "doxy": "doxycycline",
    "pan": "pantoprazole", "pan d": "pantoprazole + domperidone",
    "pan 40": "pantoprazole 40mg",
    "rantac": "ranitidine", "zinetac": "ranitidine",
    "omez": "omeprazole",
    "emeset": "ondansetron",
    "perinorm": "metoclopramide",
    "domstal": "domperidone",
    "allegra": "fexofenadine",
    "montair": "montelukast", "montair lc": "montelukast + levocetirizine",
    "okacet": "cetirizine", "alerid": "cetirizine",
    "xyzal": "levocetirizine",
    "amlip": "amlodipine", "amlong": "amlodipine",
    "stamlo": "amlodipine",
    "telma": "telmisartan", "telma h": "telmisartan + hydrochlorothiazide",
    "repace": "losartan",
    "aten": "atenolol",
    "metolar": "metoprolol", "betaloc": "metoprolol",
    "ecosprin": "aspirin", "ecosprin av": "aspirin + atorvastatin",
    "clopilet": "clopidogrel", "deplatt": "clopidogrel",
    "atorva": "atorvastatin", "tonact": "atorvastatin",
    "rozavel": "rosuvastatin", "crestor": "rosuvastatin",
    "glycomet": "metformin", "glycomet gp": "metformin + glimepiride",
    "obimet": "metformin",
    "amaryl": "glimepiride", "glimisave": "glimepiride",
    "januvia": "sitagliptin", "jalra": "vildagliptin",
    "jardiance": "empagliflozin", "forxiga": "dapagliflozin",
    "thyronorm": "levothyroxine", "eltroxin": "levothyroxine",
    "shelcal": "calcium + vitamin D",
    "becosules": "B-complex + vitamin C",
    "nurokind": "methylcobalamin",
    "methycobal": "methylcobalamin",
    "zincovit": "multivitamin + zinc",
    "evion": "vitamin E",
    "limcee": "vitamin C",
    "folvite": "folic acid",
    "dexona": "dexamethasone", "wysolone": "prednisolone",
    "medrol": "methylprednisolone",
    "deriphyllin": "theophylline + etophylline",
    "asthalin": "salbutamol", "duolin": "salbutamol + ipratropium",
    "budecort": "budesonide", "foracort": "formoterol + budesonide",
    "seroflo": "salmeterol + fluticasone",
    "sinarest": "paracetamol + chlorpheniramine + pseudoephedrine",
    "otrivin": "xylometazoline",
    "nasivion": "oxymetazoline",
    "oflox": "ofloxacin",
    "norflox tz": "norfloxacin + tinidazole",
    "betadine": "povidone-iodine",
    "volini": "diclofenac gel",
    "soframycin": "framycetin",
    "t bact": "mupirocin",
    "candid b": "clotrimazole + beclomethasone",
    "candid": "clotrimazole",
    "dermiford": "clobetasol",
}

# ── Hinglish symptom seeds (auto-loaded, no external file needed) ────────────

_SEED_HINGLISH_SYMPTOMS: dict[str, str] = {
    "bukhar": "fever", "bukhaar": "fever", "buhkhar": "fever", "buhar": "fever",
    "tez bukhar": "fever",
    "khasi": "cough", "khansi": "cough", "khaansi": "cough",
    "sukhi khansi": "dry cough",
    "sir dard": "headache", "sar dard": "headache", "sirdard": "headache",
    "sar mein dard": "headache",
    "pet dard": "abdominal pain", "pet mein dard": "abdominal pain",
    "pait dard": "abdominal pain", "pait mein dard": "abdominal pain",
    "seena dard": "chest pain", "seene mein dard": "chest pain",
    "seene mein jalan": "acidity", "jalan": "burning sensation",
    "chakkar": "dizziness", "chakkar aana": "dizziness",
    "sar ghoomna": "dizziness",
    "ulti": "vomiting", "ult": "vomiting",
    "jee machlana": "nausea", "ji machlana": "nausea",
    "jee machlaana": "nausea",
    "kamzori": "weakness", "kamjori": "weakness",
    "thakan": "fatigue", "thakaan": "fatigue", "thaka hua": "fatigue",
    "saans": "breathlessness", "saans lene mein takleef": "breathlessness",
    "saans phoolna": "breathlessness", "haanfna": "breathlessness",
    "dast": "diarrhea",
    "sardi": "cold", "nazla": "cold",
    "naak beh rahi": "runny nose", "naak beh raha": "runny nose",
    "naak band": "nasal congestion",
    "gala kharab": "sore throat", "gale mein dard": "sore throat",
    "gale mein sujan": "sore throat",
    "badan dard": "body ache", "badan mein dard": "body ache",
    "daant dard": "toothache", "dant dard": "toothache",
    "khujli": "itching", "kharish": "itching",
    "sujan": "swelling",
    "kamar dard": "back pain", "kamar mein dard": "back pain",
    "ghutne mein dard": "knee pain",
    "jodo mein dard": "joint pain",
    "haath mein dard": "hand pain",
    "haath sunn": "numbness", "haath pair sunn": "numbness",
    "pair sunn": "numbness", "jhanjhnahat": "numbness",
    "haath kaanpna": "tremor", "haath kaanpe": "tremor", "kaanpna": "tremor",
    "bhookh nahi": "loss of appetite", "bhukh nahi": "loss of appetite",
    "khana nahi khaya": "loss of appetite",
    "neend nahi": "insomnia", "neend aati nahi": "insomnia",
    "wajan kam": "weight loss", "vajan ghat raha": "weight loss",
    "raat ko paseena": "night sweats",
    "aankhon mein dard": "eye pain", "aankhon mein jalan": "eye irritation",
    "aankhein lal": "red eyes",
    "nazar dhundhli": "blurred vision", "dhundhla dikhna": "blurred vision",
    "naak se khoon": "epistaxis",
    "peeli aankhein": "jaundice", "aankhein peeli": "jaundice",
    "muh mein chaale": "mouth ulcer", "chaale": "mouth ulcer",
    "kaan mein dard": "ear pain",
    "thand lagna": "chills", "thand lag rahi": "chills",
    "kapkapi": "chills",
    "peshab mein jalan": "dysuria",
    "peshab baar baar": "urinary frequency",
    "khoon aana": "bleeding",
    "khoon ki ulti": "hematemesis",
    "kala paikhana": "melena",
    "pair mein sujan": "pedal edema",
    "seedhi mein saans": "orthopnea",
    # Devanagari
    "बुखार": "fever", "खांसी": "cough", "खाँसी": "cough", "खासी": "cough",
    "सिर दर्द": "headache", "सर दर्द": "headache",
    "सीने में दर्द": "chest pain", "सीने में जलन": "acidity",
    "जलन": "burning sensation",
    "जी मिचलाना": "nausea", "उल्टी": "vomiting",
    "चक्कर": "dizziness", "कमजोरी": "weakness", "थकान": "fatigue",
    "सांस फूलना": "breathlessness", "सांस लेने में तकलीफ": "breathlessness",
    "दस्त": "diarrhea", "सर्दी": "cold",
    "नाक बहना": "runny nose", "नाक बंद": "nasal congestion",
    "गले में दर्द": "sore throat", "गले में खराश": "sore throat",
    "बदन दर्द": "body ache", "पेट दर्द": "abdominal pain",
    "पेट में दर्द": "abdominal pain",
    "खुजली": "itching", "सूजन": "swelling",
    "कमर दर्द": "back pain",
    "भूख नहीं": "loss of appetite", "नींद नहीं": "insomnia",
    "वजन कम": "weight loss",
    "हाथ-पैर सुन्न": "numbness", "हाथ कांपना": "tremor",
    "पीली आंखें": "jaundice", "आंखों में दर्द": "eye pain",
    "घुटने में दर्द": "knee pain", "जोड़ों में दर्द": "joint pain",
    "पेशाब में जलन": "dysuria",
}

_SEED_HINGLISH_MEDICATIONS: dict[str, str] = {
    "dawai": "medication", "goli": "tablet", "syrup": "syrup",
    "injection": "injection", "cream": "cream", "ointment": "ointment",
}

_SEED_HINGLISH_DIAGNOSES: dict[str, str] = {
    "sugar ki bimari": "Diabetes Mellitus", "madhumeh": "Diabetes Mellitus",
    "bp high": "Hypertension", "bp badhna": "Hypertension",
    "lakwa": "Paralysis", "motiyabind": "Cataract",
    "safed daag": "Vitiligo", "peelia": "Jaundice",
    "dama": "Asthma",
    "शुगर": "Diabetes Mellitus", "मधुमेह": "Diabetes Mellitus",
    "मोतियाबिंद": "Cataract", "खून की कमी": "Anemia",
    "दमा": "Asthma", "पीलिया": "Jaundice",
}


# ── Module-level singleton ───────────────────────────────────────────────────

ontology = MedicalOntology()
ontology.load()
